//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.Collections.Generic;
using System.Globalization;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// ConfigBlob 写侧代码生成（编辑器 .g.cs）。每张表产出：
    /// <c>XxxSourceRow</c>——强类型的中间行（文本解析结果）；
    /// <c>XxxTableBuilder</c>——文本解析 + 按 <c>ConfigBlobSchema</c> 常量把行写成二进制。
    ///
    /// 写侧偏移全部引用读侧同一批常量，不做二次计算，因此读写不可能对不上。
    /// 与 <c>ConfigBlobWriter</c> 的交互（BeginTable / AddRow / SetXxx / EndTable）集中在
    /// 本类的 Writer* 常量里，容器 API 若有变动只需改这几行。
    /// </summary>
    public static class ConfigBlobBuilderEmitter
    {
        /// <summary>开表调用模板：{0}=表名常量，{1}=rowSize 常量。</summary>
        public const string WriterBeginTableFormat = "writer.BeginTable({0}, {1});";

        /// <summary>加行调用模板：{0}=主键表达式；返回行号，后续 SetXxx 都要带上它。</summary>
        public const string WriterAddRowFormat = "int rowIndex = writer.AddRow({0});";

        /// <summary>字段写入调用模板：{0}=SetXxx 方法名，{1}=行内偏移常量，{2}=值表达式。</summary>
        public const string WriterSetFieldFormat = "writer.{0}(rowIndex, {1}, {2});";

        /// <summary>收表调用模板。</summary>
        public const string WriterEndTable = "writer.EndTable();";

        /// <summary>生成一张表的写侧源码。</summary>
        public static CodeBuilder Emit(
            ConfigBlobLayout.TableLayout layout,
            string editorNamespace,
            string runtimeNamespace,
            string containerNamespace,
            string schemaClassName,
            string toolName)
        {
            var cb = new CodeBuilder();
            cb.WriteAutoGeneratedHeader(toolName, layout.SourcePath);
            cb.Using("System.Collections.Generic");
            cb.Using("System.Globalization");
            cb.Using("System.IO");
            cb.Using("System.Text");
            cb.Using(containerNamespace);
            cb.Using(runtimeNamespace);
            cb.BlankLine();
            cb.BeginBlock("namespace " + editorNamespace);

            EmitSourceRow(cb, layout);
            cb.BlankLine();
            EmitBuilder(cb, layout, schemaClassName);

            cb.EndBlock();
            return cb;
        }

        private static void EmitSourceRow(CodeBuilder cb, ConfigBlobLayout.TableLayout layout)
        {
            List<ConfigBlobLayout.FieldLayout> fields = layout.FieldsInDeclarationOrder;

            cb.Line("/// <summary>配置表 " + layout.TableName + " 的中间行：文本解析结果，仅在编辑器构建期存在。</summary>");
            cb.BeginBlock("public partial struct " + layout.TableName + "SourceRow");
            for (int i = 0; i < fields.Count; i++)
            {
                ConfigBlobLayout.FieldLayout field = fields[i];
                if (i > 0) cb.BlankLine();
                cb.Line("/// <summary>列 " + field.Name + "（" + field.DeclaredType + "，源表第 " + field.SourceColumnIndex + " 列）。</summary>");
                cb.Line("public " + ConfigBlobLayout.ClrTypeName(field.Kind) + " " + field.Name + ";");
            }
            cb.EndBlock();
        }

        private static void EmitBuilder(CodeBuilder cb, ConfigBlobLayout.TableLayout layout, string schemaClassName)
        {
            string rowType = layout.TableName + "SourceRow";
            string builderType = layout.TableName + "TableBuilder";
            string prefix = schemaClassName + "." + layout.TableName;
            List<ConfigBlobLayout.FieldLayout> declFields = layout.FieldsInDeclarationOrder;

            cb.Line("/// <summary>配置表 " + layout.TableName + " 的二进制构建器（文本 -> ConfigBlobWriter）。</summary>");
            cb.BeginBlock("public static partial class " + builderType);

            cb.Line("/// <summary>表名。</summary>");
            cb.Line("public const string TableName = " + prefix + "TableName;");
            cb.BlankLine();
            cb.Line("/// <summary>源表列数。</summary>");
            cb.Line("public const int ColumnCount = " + prefix + "ColumnCount;");
            cb.BlankLine();
            cb.Line("/// <summary>主键列在源表里的下标（表头识别与生成器侧同源，靠的就是这一列）。</summary>");
            cb.Line("public const int PrimaryKeyColumnIndex = " +
                    layout.PrimaryKey.SourceColumnIndex.ToString(CultureInfo.InvariantCulture) + ";");
            cb.BlankLine();

            cb.Line("/// <summary>");
            cb.Line("/// 生成本文件时源表的列名与列序。ParseText 会拿它跟源表的字段名注释行比对：");
            cb.Line("/// 列被增删或换位而生成代码没重跑时，下面这些按列下标取值的代码会整列错位，");
            cb.Line("/// 且因为多数列类型相同（都是 string/int），错位往往不会报解析错，而是把错的值写进 blob。");
            cb.Line("/// 比对失败直接抛，是为了让这种事故在导表期炸掉而不是流到线上。");
            cb.Line("/// </summary>");
            cb.Line("public static readonly string[] SourceColumns =");
            cb.Indent();
            var columnLiterals = new List<string>(declFields.Count);
            for (int i = 0; i < declFields.Count; i++) columnLiterals.Add("\"" + declFields[i].Name + "\"");
            cb.Line("{ " + string.Join(", ", columnLiterals.ToArray()) + " };");
            cb.Outdent();
            cb.BlankLine();

            cb.Line("/// <summary>读源表文件并解析成中间行；路径会带进报错消息。</summary>");
            cb.Line("public static List<" + rowType + "> ParseFile(string path)");
            cb.Indent();
            cb.Line("=> ParseText(File.ReadAllText(path, Encoding.UTF8), path);");
            cb.Outdent();
            cb.BlankLine();

            cb.Line("/// <summary>");
            cb.Line("/// 解析表文本：跳过空行，注释行里找出字段名头做列序校验，其余按 TAB 切列");
            cb.Line("/// （与 DataTableTextParser 约定一致）。找不到字段名头同样视为错误——");
            cb.Line("/// 无法确认列序时宁可停下，也不能按烘焙下标硬取。");
            cb.Line("/// </summary>");
            cb.BeginBlock("public static List<" + rowType + "> ParseText(string text, string origin = null)");
            cb.Line("var rows = new List<" + rowType + ">();");
            cb.Line("string where = string.IsNullOrEmpty(origin) ? TableName : origin;");
            cb.Line("if (string.IsNullOrEmpty(text)) return rows;");
            cb.Line("string[] lines = text.Replace(\"\\r\\n\", \"\\n\").Replace('\\r', '\\n').Split('\\n');");
            cb.Line("bool headerVerified = false;");
            cb.BeginBlock("for (int i = 0; i < lines.Length; i++)");
            cb.Line("string line = lines[i].TrimStart();");
            cb.Line("if (line.TrimEnd().Length == 0) continue;");
            cb.BeginBlock("if (line[0] == '#')");
            cb.Line("if (!headerVerified) headerVerified = TryVerifyHeader(line, where, i + 1);");
            cb.Line("continue;");
            cb.EndBlock();
            cb.BeginBlock("if (!headerVerified)");
            cb.Line("throw new EjoyFramework.Core.FrameworkException(\"" + builderType +
                    "：\" + where + \" 在首个数据行之前没有可识别的字段名注释行（应为 '# \" + string.Join(\"\\t\", SourceColumns) + \"'），\" +");
            cb.Indent();
            cb.Line("\"无法确认列序与生成代码一致。请补上字段名头，或重跑 ConfigBlob 代码生成。\");");
            cb.Outdent();
            cb.EndBlock();
            cb.Line("rows.Add(ParseRow(line, where, i + 1));");
            cb.EndBlock();
            cb.Line("return rows;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>");
            cb.Line("/// 拿一条注释行试着当字段名头。判据必须与生成器侧 ConfigBlobSchemaSource.PickHeaderRow 完全一致：");
            cb.Line("/// 列数相同、每格都是合法标识符、且主键那一格正是主键列名。");
            cb.Line("/// 少了最后一条就会两边不同源——C# 标识符允许 Unicode 字母，中文说明行照样「每格都是合法标识符」，");
            cb.Line("/// 生成期会被跳过、导表期却会被当成表头，于是同一个文件生成得出来、导表却报「表头被改」，诊断完全误导。");
            cb.Line("/// 判据一致时，说明行在两侧都只是被跳过。");
            cb.Line("/// </summary>");
            cb.BeginBlock("private static bool TryVerifyHeader(string commentLine, string where, int lineNumber)");
            cb.Line("string[] cells = commentLine.Substring(1).Split('\\t');");
            cb.Line("if (cells.Length != SourceColumns.Length) return false;");
            cb.BeginBlock("for (int c = 0; c < cells.Length; c++)");
            cb.Line("cells[c] = cells[c].Trim();");
            cb.Line("if (!IsIdentifier(cells[c])) return false;");
            cb.EndBlock();
            cb.Line("// 主键列没对上，说明这行根本不是字段名头（而非「表头被改了」），当普通注释跳过。");
            cb.Line("if (!string.Equals(cells[PrimaryKeyColumnIndex], SourceColumns[PrimaryKeyColumnIndex], System.StringComparison.OrdinalIgnoreCase))");
            cb.Indent();
            cb.Line("return false;");
            cb.Outdent();
            cb.BeginBlock("for (int c = 0; c < cells.Length; c++)");
            cb.BeginBlock("if (!string.Equals(cells[c], SourceColumns[c], System.StringComparison.Ordinal))");
            cb.Line("throw new EjoyFramework.Core.FrameworkException(\"" + builderType +
                    "：\" + where + \" 第 \" + lineNumber + \" 行的表头与生成代码不一致——第 \" + c + \" 列，\" +");
            cb.Indent();
            cb.Line("\"生成时是 '\" + SourceColumns[c] + \"'，现在是 '\" + cells[c] + \"'。列序已变，按旧下标解析会整列错位；\" +");
            cb.Line("\"请重跑 EjoyFramework/Core/CodeGen/Generate ConfigBlob。\");");
            cb.Outdent();
            cb.EndBlock();
            cb.EndBlock();
            cb.Line("return true;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>合法 C# 标识符判定，与生成器侧 ConfigBlobLayout.IsValidIdentifier 同规则。</summary>");
            cb.BeginBlock("private static bool IsIdentifier(string value)");
            cb.Line("if (string.IsNullOrEmpty(value)) return false;");
            cb.Line("if (!char.IsLetter(value[0]) && value[0] != '_') return false;");
            cb.BeginBlock("for (int i = 1; i < value.Length; i++)");
            cb.Line("if (!char.IsLetterOrDigit(value[i]) && value[i] != '_') return false;");
            cb.EndBlock();
            cb.Line("return true;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>解析单行（TAB 分隔；数值一律 InvariantCulture，避免机器区域设置影响构建产物）。</summary>");
            cb.BeginBlock("public static " + rowType + " ParseRow(string line, string where = null, int lineNumber = 0)");
            cb.Line("string[] cols = line.Split('\\t');");
            cb.BeginBlock("if (cols.Length != ColumnCount)");
            cb.Line("throw new EjoyFramework.Core.FrameworkException(\"" + builderType +
                    "：\" + Describe(where, lineNumber) + \"期望 \" + ColumnCount + \" 列，实际 \" + cols.Length + \" 列。\");");
            cb.EndBlock();
            cb.Line("var row = new " + rowType + "();");
            for (int i = 0; i < declFields.Count; i++)
            {
                ConfigBlobLayout.FieldLayout field = declFields[i];
                cb.Line("row." + field.Name + " = " +
                        ParseCall(field.Kind, "cols[" + field.SourceColumnIndex + "]", field.Name) + ";");
            }
            cb.Line("return row;");
            cb.EndBlock();
            cb.BlankLine();

            EmitParseHelpers(cb, layout, builderType);

            cb.Line("/// <summary>把中间行写入 blob；行内偏移全部取自 " + schemaClassName + "，与读侧同源。</summary>");
            cb.BeginBlock("public static void Write(IList<" + rowType + "> rows, ConfigBlobWriter writer)");
            cb.Line("if (rows == null) throw new EjoyFramework.Core.FrameworkException(\"" + builderType + ".Write: rows is null.\");");
            cb.Line("if (writer == null) throw new EjoyFramework.Core.FrameworkException(\"" + builderType + ".Write: writer is null.\");");
            cb.BlankLine();
            cb.Line("// 行序保持源表顺序；主键索引由 ConfigBlobWriter 在 Build 时按 Id 升序另行建立。");
            cb.Line(string.Format(WriterBeginTableFormat, prefix + "TableName", prefix + "RowSize"));
            cb.BeginBlock("for (int i = 0; i < rows.Count; i++)");
            cb.Line(rowType + " row = rows[i];");
            cb.Line(string.Format(WriterAddRowFormat, "row." + layout.PrimaryKey.Name));

            for (int i = 0; i < layout.Fields.Count; i++)
            {
                ConfigBlobLayout.FieldLayout field = layout.Fields[i];
                string offsetConst = prefix + "_" + field.Name + "_Offset";
                cb.Line(WriteStatement(field.Kind, offsetConst, "row." + field.Name));
            }

            cb.EndBlock();
            cb.Line(WriterEndTable);
            cb.EndBlock();

            cb.EndBlock();
        }

        /// <summary>文本列 -> 强类型的取值表达式：string 列直取，其余走带上下文的解析 helper。</summary>
        public static string ParseCall(ConfigBlobLayout.FieldKind kind, string source, string columnName)
        {
            if (kind == ConfigBlobLayout.FieldKind.String) return source;
            return ParseHelperName(kind) + "(" + source + ", \"" + columnName + "\", where, lineNumber)";
        }

        /// <summary>字段种类 -> 生成的解析 helper 名。</summary>
        public static string ParseHelperName(ConfigBlobLayout.FieldKind kind)
        {
            switch (kind)
            {
                case ConfigBlobLayout.FieldKind.Int32: return "ParseInt32";
                case ConfigBlobLayout.FieldKind.Int64: return "ParseInt64";
                case ConfigBlobLayout.FieldKind.Int16: return "ParseInt16";
                case ConfigBlobLayout.FieldKind.Byte: return "ParseByte";
                case ConfigBlobLayout.FieldKind.Bool: return "ParseBoolean";
                case ConfigBlobLayout.FieldKind.Single: return "ParseSingle";
                case ConfigBlobLayout.FieldKind.Double: return "ParseDouble";
                default:
                    throw new FrameworkException("ConfigBlobBuilderEmitter: kind " + kind + " needs no parse helper.");
            }
        }

        /// <summary>
        /// 生成本表用得到的解析 helper。一律 TryParse + 抛出「文件/行号/列名/原值/期望类型」五元组，
        /// 而不是让 int.Parse 抛一个只说 "Input string was not in a correct format" 的 FormatException——
        /// 后者在几十张表几千行里等于没有信息。
        /// </summary>
        private static void EmitParseHelpers(CodeBuilder cb, ConfigBlobLayout.TableLayout layout, string builderType)
        {
            cb.Line("/// <summary>报错前缀：把文件与行号拼成人能直接定位的样子。</summary>");
            cb.BeginBlock("private static string Describe(string where, int lineNumber)");
            cb.Line("if (string.IsNullOrEmpty(where)) where = TableName;");
            cb.Line("return lineNumber > 0 ? where + \" 第 \" + lineNumber + \" 行：\" : where + \"：\";");
            cb.EndBlock();

            var emitted = new HashSet<ConfigBlobLayout.FieldKind>();
            for (int i = 0; i < layout.FieldsInDeclarationOrder.Count; i++)
            {
                ConfigBlobLayout.FieldKind kind = layout.FieldsInDeclarationOrder[i].Kind;
                if (kind == ConfigBlobLayout.FieldKind.String) continue;
                if (!emitted.Add(kind)) continue;

                string helper = ParseHelperName(kind);
                string clr = ConfigBlobLayout.ClrTypeName(kind);
                cb.BlankLine();
                cb.Line("/// <summary>解析 " + clr + " 列；失败时报出文件、行号、列名与原值。</summary>");
                cb.BeginBlock("private static " + clr + " " + helper + "(string raw, string column, string where, int lineNumber)");
                cb.Line(TryParseCondition(kind));
                cb.Indent();
                cb.Line("return value;");
                cb.Outdent();
                cb.Line("throw new EjoyFramework.Core.FrameworkException(\"" + builderType + "：\" + Describe(where, lineNumber) +");
                cb.Indent();
                cb.Line("\"列 '\" + column + \"' 的值 \\\"\" + raw + \"\\\" 不是合法的 " + clr + "。\");");
                cb.Outdent();
                cb.EndBlock();
            }
        }

        /// <summary>单个 TryParse 判定语句（成功则落到紧随其后的 return value）。</summary>
        private static string TryParseCondition(ConfigBlobLayout.FieldKind kind)
        {
            switch (kind)
            {
                case ConfigBlobLayout.FieldKind.Int32:
                    return "if (int.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out int value))";
                case ConfigBlobLayout.FieldKind.Int64:
                    return "if (long.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out long value))";
                case ConfigBlobLayout.FieldKind.Int16:
                    return "if (short.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out short value))";
                case ConfigBlobLayout.FieldKind.Byte:
                    return "if (byte.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out byte value))";
                case ConfigBlobLayout.FieldKind.Bool:
                    return "if (bool.TryParse(raw.Trim(), out bool value))";
                case ConfigBlobLayout.FieldKind.Single:
                    return "if (float.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out float value))";
                case ConfigBlobLayout.FieldKind.Double:
                    return "if (double.TryParse(raw, NumberStyles.Float, CultureInfo.InvariantCulture, out double value))";
                default:
                    throw new FrameworkException("ConfigBlobBuilderEmitter: unsupported kind " + kind + ".");
            }
        }

        /// <summary>单字段写入语句（走 ConfigBlobWriter 的强类型 SetXxx，字节序与字符串入池由容器负责）。</summary>
        public static string WriteStatement(ConfigBlobLayout.FieldKind kind, string offsetConst, string valueExpr)
        {
            return string.Format(WriterSetFieldFormat, WriterSetMethod(kind), offsetConst, valueExpr);
        }

        /// <summary>字段种类 -> ConfigBlobWriter 的写入方法名。</summary>
        public static string WriterSetMethod(ConfigBlobLayout.FieldKind kind)
        {
            switch (kind)
            {
                case ConfigBlobLayout.FieldKind.Int32: return "SetInt32";
                case ConfigBlobLayout.FieldKind.Int64: return "SetInt64";
                case ConfigBlobLayout.FieldKind.Int16: return "SetInt16";
                case ConfigBlobLayout.FieldKind.Byte: return "SetByte";
                case ConfigBlobLayout.FieldKind.Bool: return "SetBoolean";
                case ConfigBlobLayout.FieldKind.Single: return "SetSingle";
                case ConfigBlobLayout.FieldKind.Double: return "SetDouble";
                case ConfigBlobLayout.FieldKind.String: return "SetString";
                default:
                    throw new FrameworkException("ConfigBlobBuilderEmitter: unsupported kind " + kind + ".");
            }
        }
    }
}
