//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using EjoyFramework.Core.Serialization;
using EjoyFramework.Core.Unity;
using UnityEditor;
using UnityEngine;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// Generates IMonoBehaviourSnapshot implementations for partial MonoBehaviour classes marked with
    /// [GenerateMonoBehaviourSnapshot]. The generator uses UnitySerializedMemberPolicy for member discovery
    /// and keeps Unity object reference identity delegated to IUnityObjectReferenceResolver.
    /// </summary>
    public sealed class MonoBehaviourSnapshotGenerator : ICodeGenerator
    {
        public const string OutputDir = CodeGenTypeUtil.DefaultAssemblyGeneratedRoot + "/MonoBehaviourSnapshots";
        private const string ToolName = "EjoyFramework.Core.Unity.Editor.CodeGen.MonoBehaviourSnapshotGenerator";
        private readonly string m_OutputDir;
        private readonly List<Type> m_CandidateTypes;
        private readonly bool m_UseAssemblyOutput;

        public MonoBehaviourSnapshotGenerator()
        {
            m_UseAssemblyOutput = true;
        }

        public MonoBehaviourSnapshotGenerator(string outputDir)
            : this(outputDir, null)
        {
        }

        public MonoBehaviourSnapshotGenerator(string outputDir, IEnumerable<Type> candidateTypes)
        {
            if (string.IsNullOrEmpty(outputDir)) throw new ArgumentException("outputDir is null or empty.", nameof(outputDir));
            m_OutputDir = outputDir;
            m_CandidateTypes = candidateTypes == null ? null : new List<Type>(candidateTypes);
            m_UseAssemblyOutput = false;
        }

        public string Id => "monoBehaviourSnapshot";
        public string DisplayName => "MonoBehaviour Snapshot";
        public string Description => "[GenerateMonoBehaviourSnapshot] -> CaptureSnapshot/RestoreSnapshot for Unity serialized fields.";

        [MenuItem("EjoyFramework/Core/CodeGen/Generate MonoBehaviour Snapshots")]
        public static void GenerateMenu()
        {
            CodeGenHub.RunOne(new MonoBehaviourSnapshotGenerator());
        }

        public CodeGenResult Run()
        {
            var warnings = new List<string>();
            int written = 0, unchanged = 0, skipped = 0;

            foreach (Type type in GetCandidateTypes())
            {
                if (type.IsNested)
                {
                    warnings.Add(type.FullName + ": nested MonoBehaviour snapshot types are not supported.");
                    skipped++;
                    continue;
                }

                if (type.ContainsGenericParameters)
                {
                    warnings.Add(type.FullName + ": open generic MonoBehaviour snapshot types are not supported.");
                    skipped++;
                    continue;
                }

                if (!typeof(MonoBehaviour).IsAssignableFrom(type))
                {
                    warnings.Add(type.FullName + ": [GenerateMonoBehaviourSnapshot] requires a MonoBehaviour type.");
                    skipped++;
                    continue;
                }

                var members = UnitySerializedMemberPolicy.GetSerializedFields(type);
                members = FilterAccessibleMembers(type, members, warnings, ref skipped);

                var cb = new CodeBuilder();
                cb.WriteAutoGeneratedHeader(ToolName);
                cb.Using("EjoyFramework.Core.Serialization");
                cb.Using("EjoyFramework.Core.Unity");
                cb.BlankLine();

                bool hasNamespace = !string.IsNullOrEmpty(type.Namespace);
                if (hasNamespace) cb.BeginBlock("namespace " + type.Namespace);

                string access = type.IsPublic ? "public" : "internal";
                cb.BeginBlock(access + " partial class " + type.Name + " : IMonoBehaviourSnapshot");

                int memberSkips = EmitCapture(cb, type, members, warnings);
                cb.BlankLine();
                EmitRestore(cb, type, members, warnings);
                skipped += memberSkips;

                cb.EndBlock();
                if (hasNamespace) cb.EndBlock();

                string path;
                if (!TryGetOutputPath(type, warnings, out path))
                {
                    skipped++;
                    continue;
                }
                if (cb.WriteIfChanged(path)) written++;
                else unchanged++;
            }

            return new CodeGenResult
            {
                Written = written,
                Unchanged = unchanged,
                Skipped = skipped,
                Messages = warnings.ToArray(),
            };
        }

        private IEnumerable<Type> GetCandidateTypes()
        {
            if (m_CandidateTypes != null) return m_CandidateTypes;
            return CodeGenTypeUtil.FindTypesWithAttribute(typeof(GenerateMonoBehaviourSnapshotAttribute));
        }

        private static List<CodeGenMemberDescriptor> FilterAccessibleMembers(
            Type targetType,
            List<CodeGenMemberDescriptor> members,
            List<string> warnings,
            ref int skipped)
        {
            var result = new List<CodeGenMemberDescriptor>(members.Count);
            var names = new HashSet<string>(StringComparer.Ordinal);

            for (int i = 0; i < members.Count; i++)
            {
                CodeGenMemberDescriptor member = members[i];
                var field = member.MemberInfo as FieldInfo;
                if (field == null) continue;

                if (!CanAccessFieldFromGeneratedPartial(targetType, field))
                {
                    warnings.Add(targetType.Name + "." + member.Name
                        + ": inherited field is not accessible from generated partial code.");
                    skipped++;
                    continue;
                }

                if (Attribute.IsDefined(field, typeof(SerializeReference), false)
                    && !CanGenerateSerializeReference(field.FieldType, targetType.Assembly, out string serializeReferenceReason))
                {
                    warnings.Add(targetType.Name + "." + member.Name + ": " + serializeReferenceReason);
                    skipped++;
                    continue;
                }

                if (!names.Add(member.Name))
                {
                    warnings.Add(targetType.Name + "." + member.Name
                        + ": duplicate serialized field name is ambiguous for generated code.");
                    skipped++;
                    continue;
                }

                result.Add(member);
            }

            return result;
        }

        private static bool CanAccessFieldFromGeneratedPartial(Type targetType, FieldInfo field)
        {
            if (field.DeclaringType == targetType) return true;
            if (field.IsPublic || field.IsFamily || field.IsFamilyOrAssembly) return true;
            if (field.IsAssembly || field.IsFamilyAndAssembly)
            {
                return field.DeclaringType != null && field.DeclaringType.Assembly == targetType.Assembly;
            }
            return false;
        }

        private static int EmitCapture(
            CodeBuilder cb,
            Type type,
            List<CodeGenMemberDescriptor> members,
            List<string> warnings)
        {
            cb.BeginBlock("public void CaptureSnapshot(ByteBuffer buffer, MonoBehaviourSnapshotContext context)");
            var ctx = new EmitCtx(cb, type, warnings);
            for (int i = 0; i < members.Count; i++)
            {
                CodeGenMemberDescriptor member = members[i];
                bool serializeReference = IsSerializeReferenceMember(member);
                if (!IsSupportedType(member.MemberType, type.Assembly, out string reason, serializeReference))
                {
                    ctx.WarnSkip(member.Name, member.MemberType, reason);
                    continue;
                }
                EmitWrite(ctx, member.MemberType, "this." + member.Name, member.Name, serializeReference);
            }
            cb.EndBlock();
            return ctx.SkippedMembers;
        }

        private static void EmitRestore(
            CodeBuilder cb,
            Type type,
            List<CodeGenMemberDescriptor> members,
            List<string> warnings)
        {
            cb.BeginBlock("public void RestoreSnapshot(ByteBuffer buffer, MonoBehaviourSnapshotContext context)");
            var ctx = new EmitCtx(cb, type, warnings);
            for (int i = 0; i < members.Count; i++)
            {
                CodeGenMemberDescriptor member = members[i];
                bool serializeReference = IsSerializeReferenceMember(member);
                if (!IsSupportedType(member.MemberType, type.Assembly, out _, serializeReference)) continue;
                EmitRead(ctx, member.MemberType, "this." + member.Name, member.Name, serializeReference);
            }
            cb.EndBlock();
        }

        private static void EmitWrite(
            EmitCtx ctx,
            Type type,
            string expr,
            string memberName,
            bool allowConcretePolymorphism = false)
        {
            CodeBuilder cb = ctx.Cb;

            string scalar = CodeGenBinaryTypeSupport.ScalarWriteCall(type, expr);
            if (scalar != null) { cb.Line(scalar); return; }

            if (type.IsEnum)
            {
                Type underlying = Enum.GetUnderlyingType(type);
                cb.Line("buffer." + CodeGenBinaryTypeSupport.ScalarWriteMethod(underlying) + "(("
                    + CodeGenTypeUtil.TypeName(underlying) + ")" + expr + ");");
                return;
            }

            if (CodeGenBinaryTypeSupport.TryWriteUnityValue(cb, type, expr)) return;

            if (IsUnityObjectReference(type))
            {
                cb.BeginBlock("if (" + expr + " == null)");
                cb.Line("buffer.WriteString(null);");
                cb.EndBlock();
                cb.BeginBlock("else");
                cb.Line("buffer.WriteString(MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, \""
                    + memberName + "\").ToReference(" + expr + "));");
                cb.EndBlock();
                return;
            }

            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                type,
                ctx.GeneratedAssembly,
                out List<Type> polymorphicCandidates,
                out _,
                allowConcretePolymorphism))
            {
                CodeGenPolymorphicTypeSupport.EmitWrite(cb, polymorphicCandidates, expr, memberName, ctx.Next());
                return;
            }

            if (IsSerializableComposite(type))
            {
                if (type.IsValueType)
                {
                    cb.Line(expr + ".Serialize(buffer);");
                }
                else
                {
                    cb.Line("buffer.WriteBool(" + expr + " != null);");
                    cb.BeginBlock("if (" + expr + " != null)");
                    cb.Line(expr + ".Serialize(buffer);");
                    cb.EndBlock();
                }
                return;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                EmitWriteCollection(ctx, shape, expr, memberName, allowConcretePolymorphism);
            }
        }

        private static void EmitWriteCollection(
            EmitCtx ctx,
            CodeGenCollectionShape shape,
            string expr,
            string memberName,
            bool allowConcretePolymorphism)
        {
            CodeBuilder cb = ctx.Cb;
            int n = ctx.Next();
            string countExpr = shape.Kind == CodeGenCollectionKind.Array ? expr + ".Length" : expr + ".Count";

            cb.Line("buffer.WriteInt(" + expr + " != null ? " + countExpr + " : -1);");
            cb.BeginBlock("if (" + expr + " != null)");
            CodeGenBinaryTypeSupport.EmitWriteEqualityComparerGuard(cb, shape, expr, n, memberName);

            if (shape.IsDictionary)
            {
                string keyValueName = "System.Collections.Generic.KeyValuePair<"
                    + CodeGenTypeUtil.TypeName(shape.KeyType) + ", "
                    + CodeGenTypeUtil.TypeName(shape.ValueType) + ">";
                string items = "_items" + n;
                cb.Line("var " + items + " = new System.Collections.Generic.List<" + keyValueName + ">(" + expr + ");");
                string compare;
                CodeGenTypeUtil.TryGetDeterministicCompareExpression(
                    shape.KeyType,
                    "_a" + n + ".Key",
                    "_b" + n + ".Key",
                    out compare);
                cb.Line(items + ".Sort((_a" + n + ", _b" + n + ") => " + compare + ");");
                cb.BeginBlock("foreach (" + keyValueName + " _kv" + n + " in " + items + ")");
                EmitWrite(ctx, shape.KeyType, "_kv" + n + ".Key", memberName, allowConcretePolymorphism);
                EmitWrite(ctx, shape.ValueType, "_kv" + n + ".Value", memberName, allowConcretePolymorphism);
                cb.EndBlock();
            }
            else if (shape.Kind == CodeGenCollectionKind.HashSet)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                string items = "_items" + n;
                cb.Line("var " + items + " = new System.Collections.Generic.List<" + elementName + ">(" + expr + ");");
                string compare;
                CodeGenTypeUtil.TryGetDeterministicCompareExpression(
                    shape.ElementType,
                    "_a" + n,
                    "_b" + n,
                    out compare);
                cb.Line(items + ".Sort((_a" + n + ", _b" + n + ") => " + compare + ");");
                cb.BeginBlock("foreach (" + elementName + " _e" + n + " in " + items + ")");
                EmitWrite(ctx, shape.ElementType, "_e" + n, memberName, allowConcretePolymorphism);
                cb.EndBlock();
            }
            else
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.BeginBlock("foreach (" + elementName + " _e" + n + " in " + expr + ")");
                EmitWrite(ctx, shape.ElementType, "_e" + n, memberName, allowConcretePolymorphism);
                cb.EndBlock();
            }

            cb.EndBlock();
        }

        private static void EmitRead(
            EmitCtx ctx,
            Type type,
            string target,
            string memberName,
            bool allowConcretePolymorphism = false)
        {
            CodeBuilder cb = ctx.Cb;

            string scalarRead = CodeGenBinaryTypeSupport.ScalarReadExpr(type);
            if (scalarRead != null) { cb.Line(target + " = " + scalarRead + ";"); return; }

            if (type.IsEnum)
            {
                Type underlying = Enum.GetUnderlyingType(type);
                cb.Line(target + " = (" + CodeGenTypeUtil.TypeName(type) + ")buffer."
                    + CodeGenBinaryTypeSupport.ScalarReadMethod(underlying) + "();");
                return;
            }

            if (CodeGenBinaryTypeSupport.TryReadUnityValue(cb, type, target, ctx.Next().ToString())) return;

            if (IsUnityObjectReference(type))
            {
                int refIndex = ctx.Next();
                cb.Line("string _ref" + refIndex + " = buffer.ReadString();");
                cb.BeginBlock("if (_ref" + refIndex + " == null)");
                cb.Line(target + " = null;");
                cb.EndBlock();
                cb.BeginBlock("else");
                cb.Line(target + " = (" + CodeGenTypeUtil.TypeName(type)
                    + ")MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, \""
                    + memberName + "\").FromReference(_ref" + refIndex + ", typeof("
                    + CodeGenTypeUtil.TypeName(type) + "));");
                cb.EndBlock();
                return;
            }

            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                type,
                ctx.GeneratedAssembly,
                out List<Type> polymorphicCandidates,
                out _,
                allowConcretePolymorphism))
            {
                CodeGenPolymorphicTypeSupport.EmitRead(cb, polymorphicCandidates, target, memberName, ctx.Next());
                return;
            }

            if (IsSerializableComposite(type))
            {
                string typeName = CodeGenTypeUtil.TypeName(type);
                if (type.IsValueType)
                {
                    int valueIndex = ctx.Next();
                    cb.Line("var _v" + valueIndex + " = new " + typeName + "();");
                    cb.Line("_v" + valueIndex + ".Deserialize(buffer);");
                    cb.Line(target + " = _v" + valueIndex + ";");
                }
                else
                {
                    cb.BeginBlock("if (buffer.ReadBool())");
                    cb.Line(target + " = new " + typeName + "();");
                    cb.Line(target + ".Deserialize(buffer);");
                    cb.EndBlock();
                    cb.BeginBlock("else");
                    cb.Line(target + " = null;");
                    cb.EndBlock();
                }
                return;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                EmitReadCollection(ctx, shape, target, memberName, allowConcretePolymorphism);
            }
        }

        private static void EmitReadCollection(
            EmitCtx ctx,
            CodeGenCollectionShape shape,
            string target,
            string memberName,
            bool allowConcretePolymorphism)
        {
            CodeBuilder cb = ctx.Cb;
            int n = ctx.Next();

            cb.Line("int _n" + n + " = buffer.ReadInt();");
            cb.BeginBlock("if (_n" + n + " < 0)");
            cb.Line(target + " = null;");
            cb.EndBlock();
            cb.BeginBlock("else");

            if (shape.Kind == CodeGenCollectionKind.Array)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _arr" + n + " = new " + elementName + "[_n" + n + "];");
                cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
                EmitRead(ctx, shape.ElementType, "_arr" + n + "[_i" + n + "]", memberName, allowConcretePolymorphism);
                cb.EndBlock();
                cb.Line(target + " = _arr" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.List)
            {
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.List", "_list", ".Add", true, target, memberName, n, allowConcretePolymorphism);
            }
            else if (shape.Kind == CodeGenCollectionKind.HashSet)
            {
                string comparer = CodeGenBinaryTypeSupport.EmitReadEqualityComparer(cb, shape, n, memberName);
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.HashSet", "_set", ".Add", false, target, memberName, n, allowConcretePolymorphism, comparer);
            }
            else if (shape.Kind == CodeGenCollectionKind.Queue)
            {
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.Queue", "_queue", ".Enqueue", true, target, memberName, n, allowConcretePolymorphism);
            }
            else if (shape.Kind == CodeGenCollectionKind.Stack)
            {
                EmitReadStack(ctx, shape.ElementType, target, memberName, n, allowConcretePolymorphism);
            }
            else if (shape.Kind == CodeGenCollectionKind.Dictionary)
            {
                EmitReadDictionary(ctx, shape, target, memberName, n, allowConcretePolymorphism);
            }

            cb.EndBlock();
        }

        private static void EmitReadAddCollection(
            EmitCtx ctx,
            Type elementType,
            string collectionTypeName,
            string variablePrefix,
            string addMethod,
            bool useCapacity,
            string target,
            string memberName,
            int n,
            bool allowConcretePolymorphism,
            string comparer = null)
        {
            CodeBuilder cb = ctx.Cb;
            string elementName = CodeGenTypeUtil.TypeName(elementType);
            string variable = variablePrefix + n;
            string ctorArg = comparer ?? (useCapacity ? "_n" + n : string.Empty);
            cb.Line("var " + variable + " = new " + collectionTypeName + "<" + elementName + ">(" + ctorArg + ");");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            cb.Line(elementName + " _e" + n + ";");
            EmitRead(ctx, elementType, "_e" + n, memberName, allowConcretePolymorphism);
            cb.Line(variable + addMethod + "(_e" + n + ");");
            cb.EndBlock();
            cb.Line(target + " = " + variable + ";");
        }

        private static void EmitReadStack(
            EmitCtx ctx,
            Type elementType,
            string target,
            string memberName,
            int n,
            bool allowConcretePolymorphism)
        {
            CodeBuilder cb = ctx.Cb;
            string elementName = CodeGenTypeUtil.TypeName(elementType);
            cb.Line("var _items" + n + " = new " + elementName + "[_n" + n + "];");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            EmitRead(ctx, elementType, "_items" + n + "[_i" + n + "]", memberName, allowConcretePolymorphism);
            cb.EndBlock();
            cb.Line("var _stack" + n + " = new System.Collections.Generic.Stack<" + elementName + ">(_n" + n + ");");
            cb.BeginBlock("for (int _i" + n + " = _n" + n + " - 1; _i" + n + " >= 0; _i" + n + "--)");
            cb.Line("_stack" + n + ".Push(_items" + n + "[_i" + n + "]);");
            cb.EndBlock();
            cb.Line(target + " = _stack" + n + ";");
        }

        private static void EmitReadDictionary(
            EmitCtx ctx,
            CodeGenCollectionShape shape,
            string target,
            string memberName,
            int n,
            bool allowConcretePolymorphism)
        {
            CodeBuilder cb = ctx.Cb;
            string keyName = CodeGenTypeUtil.TypeName(shape.KeyType);
            string valueName = CodeGenTypeUtil.TypeName(shape.ValueType);
            string comparer = CodeGenBinaryTypeSupport.EmitReadEqualityComparer(cb, shape, n, memberName);
            cb.Line("var _dict" + n + " = new System.Collections.Generic.Dictionary<" + keyName + ", " + valueName + ">(_n" + n + ", " + comparer + ");");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            cb.Line(keyName + " _key" + n + ";");
            cb.Line(valueName + " _value" + n + ";");
            EmitRead(ctx, shape.KeyType, "_key" + n, memberName, allowConcretePolymorphism);
            EmitRead(ctx, shape.ValueType, "_value" + n, memberName, allowConcretePolymorphism);
            cb.Line("_dict" + n + ".Add(_key" + n + ", _value" + n + ");");
            cb.EndBlock();
            cb.Line(target + " = _dict" + n + ";");
        }

        private static bool IsSupportedType(
            Type type,
            Assembly generatedAssembly,
            out string reason,
            bool allowConcretePolymorphism = false)
        {
            if (type == null)
            {
                reason = "null type";
                return false;
            }

            if (CodeGenBinaryTypeSupport.ScalarWriteMethod(type) != null
                || type.IsEnum
                || CodeGenBinaryTypeSupport.IsUnityValueType(type)
                || IsUnityObjectReference(type))
            {
                reason = null;
                return true;
            }
            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                type,
                generatedAssembly,
                out _,
                out reason,
                allowConcretePolymorphism))
            {
                return true;
            }
            if (CodeGenPolymorphicTypeSupport.IsPolymorphicContract(type)) return false;
            if (IsSerializableComposite(type))
            {
                if (CanDeserializeComposite(type, generatedAssembly, out reason)) return true;
                return false;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                if (shape.IsDictionary)
                {
                    if (!IsSupportedType(shape.KeyType, generatedAssembly, out reason, allowConcretePolymorphism))
                    {
                        reason = "unsupported dictionary key type: " + reason;
                        return false;
                    }
                    if (!CodeGenTypeUtil.HasDeterministicComparer(shape.KeyType))
                    {
                        reason = "dictionary key type must have a deterministic comparer";
                        return false;
                    }
                    if (!IsSupportedType(shape.ValueType, generatedAssembly, out reason, allowConcretePolymorphism))
                    {
                        reason = "unsupported dictionary value type: " + reason;
                        return false;
                    }
                    return true;
                }

                if (!IsSupportedType(shape.ElementType, generatedAssembly, out reason, allowConcretePolymorphism))
                {
                    reason = "unsupported collection element type: " + reason;
                    return false;
                }
                if (shape.Kind == CodeGenCollectionKind.HashSet
                    && !CodeGenTypeUtil.HasDeterministicComparer(shape.ElementType))
                {
                    reason = "hash set element type must have a deterministic comparer";
                    return false;
                }
                return true;
            }

            reason = "unsupported type";
            return false;
        }

        private static bool IsSerializableComposite(Type type)
        {
            return CodeGenPolymorphicTypeSupport.IsSerializableComposite(type);
        }

        private static bool IsUnityObjectReference(Type type)
        {
            return typeof(UnityEngine.Object).IsAssignableFrom(type);
        }

        private bool TryGetOutputPath(Type type, List<string> warnings, out string path)
        {
            if (!m_UseAssemblyOutput)
            {
                path = Path.Combine(m_OutputDir, CodeGenTypeUtil.GeneratedFileName(type));
                return true;
            }

            string reason;
            if (CodeGenTypeUtil.TryGetAssemblyGeneratedPath(
                type,
                "MonoBehaviourSnapshots",
                CodeGenTypeUtil.GeneratedFileName(type),
                out path,
                out reason))
            {
                return true;
            }

            warnings.Add(type.FullName + ": " + reason + " Skipped.");
            return false;
        }

        private static bool CanGenerateSerializeReference(Type type, Assembly generatedAssembly, out string reason)
        {
            reason = null;
            if (type == null)
            {
                reason = "[SerializeReference] field has no type information.";
                return false;
            }
            if (type.IsValueType)
            {
                reason = "[SerializeReference] value types are not supported by snapshot generation.";
                return false;
            }
            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                if (shape.IsDictionary)
                {
                    if (!CanGenerateSerializeReference(shape.KeyType, generatedAssembly, out reason))
                    {
                        reason = "unsupported [SerializeReference] dictionary key: " + reason;
                        return false;
                    }
                    if (!CanGenerateSerializeReference(shape.ValueType, generatedAssembly, out reason))
                    {
                        reason = "unsupported [SerializeReference] dictionary value: " + reason;
                        return false;
                    }
                    return true;
                }

                if (!CanGenerateSerializeReference(shape.ElementType, generatedAssembly, out reason))
                {
                    reason = "unsupported [SerializeReference] collection element: " + reason;
                    return false;
                }
                return true;
            }
            if (!type.IsSealed
                && !CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                    type,
                    generatedAssembly,
                    out _,
                    out reason,
                    true))
            {
                reason = "[SerializeReference] managed polymorphism has no generated concrete candidates: " + reason;
                return false;
            }
            return true;
        }

        private static bool IsSerializeReferenceMember(CodeGenMemberDescriptor member)
        {
            return member.MemberInfo != null
                && Attribute.IsDefined(member.MemberInfo, typeof(SerializeReference), false);
        }

        private static bool CanDeserializeComposite(Type type, Assembly generatedAssembly, out string reason)
        {
            return CodeGenPolymorphicTypeSupport.CanDeserializeConcreteComposite(type, generatedAssembly, out reason);
        }

        private sealed class EmitCtx
        {
            public readonly CodeBuilder Cb;
            private readonly Type m_Type;
            private readonly List<string> m_Warnings;
            private int m_Counter;

            public int SkippedMembers { get; private set; }
            public Assembly GeneratedAssembly => m_Type.Assembly;

            public EmitCtx(CodeBuilder cb, Type type, List<string> warnings)
            {
                Cb = cb;
                m_Type = type;
                m_Warnings = warnings;
            }

            public int Next()
            {
                return m_Counter++;
            }

            public void WarnSkip(string memberName, Type memberType, string reason)
            {
                SkippedMembers++;
                m_Warnings.Add(m_Type.Name + "." + memberName + ": skipped member type '"
                    + CodeGenTypeUtil.TypeName(memberType) + "' (" + reason + ").");
            }
        }
    }
}
