//------------------------------------------------------------
// AUTO-GENERATED by EjoyFramework.Core.Unity.Editor.CodeGen.MonoBehaviourSnapshotGenerator
// DO NOT EDIT - changes will be overwritten on next regen
//------------------------------------------------------------

using EjoyFramework.Core.Serialization;
using EjoyFramework.Core.Unity;

namespace EjoyFramework.Tests.CodeGenSamples
{
    public partial class MonoBehaviourSnapshotSampleComponent : IMonoBehaviourSnapshot
    {
        public void CaptureSnapshot(ByteBuffer buffer, MonoBehaviourSnapshotContext context)
        {
            buffer.WriteInt(this.IntValue);
            buffer.WriteLong(this.LongValue);
            buffer.WriteFloat(this.FloatValue);
            buffer.WriteDouble(this.DoubleValue);
            buffer.WriteBool(this.BoolValue);
            buffer.WriteUShort((ushort)this.CharValue);
            buffer.WriteString(this.StringValue);
            buffer.WriteByte((System.Byte)this.Mode);
            buffer.WriteFloat(this.Vector2Value.x);
            buffer.WriteFloat(this.Vector2Value.y);
            buffer.WriteFloat(this.Vector3Value.x);
            buffer.WriteFloat(this.Vector3Value.y);
            buffer.WriteFloat(this.Vector3Value.z);
            buffer.WriteFloat(this.Vector4Value.x);
            buffer.WriteFloat(this.Vector4Value.y);
            buffer.WriteFloat(this.Vector4Value.z);
            buffer.WriteFloat(this.Vector4Value.w);
            buffer.WriteInt(this.Vector2IntValue.x);
            buffer.WriteInt(this.Vector2IntValue.y);
            buffer.WriteInt(this.Vector3IntValue.x);
            buffer.WriteInt(this.Vector3IntValue.y);
            buffer.WriteInt(this.Vector3IntValue.z);
            buffer.WriteFloat(this.RotationValue.x);
            buffer.WriteFloat(this.RotationValue.y);
            buffer.WriteFloat(this.RotationValue.z);
            buffer.WriteFloat(this.RotationValue.w);
            buffer.WriteFloat(this.ColorValue.r);
            buffer.WriteFloat(this.ColorValue.g);
            buffer.WriteFloat(this.ColorValue.b);
            buffer.WriteFloat(this.ColorValue.a);
            buffer.WriteByte(this.Color32Value.r);
            buffer.WriteByte(this.Color32Value.g);
            buffer.WriteByte(this.Color32Value.b);
            buffer.WriteByte(this.Color32Value.a);
            buffer.WriteFloat(this.RectValue.x);
            buffer.WriteFloat(this.RectValue.y);
            buffer.WriteFloat(this.RectValue.width);
            buffer.WriteFloat(this.RectValue.height);
            buffer.WriteInt(this.IntArray != null ? this.IntArray.Length : -1);
            if (this.IntArray != null)
            {
                for (int _i0 = 0; _i0 < this.IntArray.Length; _i0++)
                {
                    buffer.WriteInt(this.IntArray[_i0]);
                }
            }
            buffer.WriteInt(this.Vector3Array != null ? this.Vector3Array.Length : -1);
            if (this.Vector3Array != null)
            {
                for (int _i1 = 0; _i1 < this.Vector3Array.Length; _i1++)
                {
                    buffer.WriteFloat(this.Vector3Array[_i1].x);
                    buffer.WriteFloat(this.Vector3Array[_i1].y);
                    buffer.WriteFloat(this.Vector3Array[_i1].z);
                }
            }
            buffer.WriteInt(this.StringList != null ? this.StringList.Count : -1);
            if (this.StringList != null)
            {
                for (int _i2 = 0; _i2 < this.StringList.Count; _i2++)
                {
                    buffer.WriteString(this.StringList[_i2]);
                }
            }
            buffer.WriteBool(this.Payload != null);
            if (this.Payload != null)
            {
                this.Payload.Serialize(buffer);
            }
            buffer.WriteInt(this.PayloadList != null ? this.PayloadList.Count : -1);
            if (this.PayloadList != null)
            {
                for (int _i3 = 0; _i3 < this.PayloadList.Count; _i3++)
                {
                    buffer.WriteBool(this.PayloadList[_i3] != null);
                    if (this.PayloadList[_i3] != null)
                    {
                        this.PayloadList[_i3].Serialize(buffer);
                    }
                }
            }
            if (this.Target == null)
            {
                buffer.WriteString(null);
            }
            else
            {
                buffer.WriteString(MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, "Target").ToReference(this.Target));
            }
            buffer.WriteInt(this.Targets != null ? this.Targets.Count : -1);
            if (this.Targets != null)
            {
                for (int _i4 = 0; _i4 < this.Targets.Count; _i4++)
                {
                    if (this.Targets[_i4] == null)
                    {
                        buffer.WriteString(null);
                    }
                    else
                    {
                        buffer.WriteString(MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, "Targets").ToReference(this.Targets[_i4]));
                    }
                }
            }
            buffer.WriteInt(this.m_PrivateInt);
            buffer.WriteFloat(this.m_PrivatePosition.x);
            buffer.WriteFloat(this.m_PrivatePosition.y);
            buffer.WriteFloat(this.m_PrivatePosition.z);
            buffer.WriteInt(this.m_PrivateScores != null ? this.m_PrivateScores.Count : -1);
            if (this.m_PrivateScores != null)
            {
                for (int _i5 = 0; _i5 < this.m_PrivateScores.Count; _i5++)
                {
                    buffer.WriteInt(this.m_PrivateScores[_i5]);
                }
            }
        }

        public void RestoreSnapshot(ByteBuffer buffer, MonoBehaviourSnapshotContext context)
        {
            this.IntValue = buffer.ReadInt();
            this.LongValue = buffer.ReadLong();
            this.FloatValue = buffer.ReadFloat();
            this.DoubleValue = buffer.ReadDouble();
            this.BoolValue = buffer.ReadBool();
            this.CharValue = (char)buffer.ReadUShort();
            this.StringValue = buffer.ReadString();
            this.Mode = (EjoyFramework.Tests.CodeGenSamples.SnapshotSampleMode)buffer.ReadByte();
            this.Vector2Value = new UnityEngine.Vector2(buffer.ReadFloat(), buffer.ReadFloat());
            this.Vector3Value = new UnityEngine.Vector3(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            this.Vector4Value = new UnityEngine.Vector4(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            this.Vector2IntValue = new UnityEngine.Vector2Int(buffer.ReadInt(), buffer.ReadInt());
            this.Vector3IntValue = new UnityEngine.Vector3Int(buffer.ReadInt(), buffer.ReadInt(), buffer.ReadInt());
            this.RotationValue = new UnityEngine.Quaternion(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            this.ColorValue = new UnityEngine.Color(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            this.Color32Value = new UnityEngine.Color32(buffer.ReadByte(), buffer.ReadByte(), buffer.ReadByte(), buffer.ReadByte());
            this.RectValue = new UnityEngine.Rect(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            int _n0 = buffer.ReadInt();
            if (_n0 < 0)
            {
                this.IntArray = null;
            }
            else
            {
                var _arr0 = new System.Int32[_n0];
                for (int _i0 = 0; _i0 < _n0; _i0++)
                {
                    _arr0[_i0] = buffer.ReadInt();
                }
                this.IntArray = _arr0;
            }
            int _n1 = buffer.ReadInt();
            if (_n1 < 0)
            {
                this.Vector3Array = null;
            }
            else
            {
                var _arr1 = new UnityEngine.Vector3[_n1];
                for (int _i1 = 0; _i1 < _n1; _i1++)
                {
                    _arr1[_i1] = new UnityEngine.Vector3(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
                }
                this.Vector3Array = _arr1;
            }
            int _n2 = buffer.ReadInt();
            if (_n2 < 0)
            {
                this.StringList = null;
            }
            else
            {
                var _list2 = new System.Collections.Generic.List<System.String>(_n2);
                for (int _i2 = 0; _i2 < _n2; _i2++)
                {
                    System.String _e2;
                    _e2 = buffer.ReadString();
                    _list2.Add(_e2);
                }
                this.StringList = _list2;
            }
            if (buffer.ReadBool())
            {
                this.Payload = new EjoyFramework.Tests.CodeGenSamples.SnapshotNestedPayload();
                this.Payload.Deserialize(buffer);
            }
            else
            {
                this.Payload = null;
            }
            int _n3 = buffer.ReadInt();
            if (_n3 < 0)
            {
                this.PayloadList = null;
            }
            else
            {
                var _list3 = new System.Collections.Generic.List<EjoyFramework.Tests.CodeGenSamples.SnapshotNestedPayload>(_n3);
                for (int _i3 = 0; _i3 < _n3; _i3++)
                {
                    EjoyFramework.Tests.CodeGenSamples.SnapshotNestedPayload _e3;
                    if (buffer.ReadBool())
                    {
                        _e3 = new EjoyFramework.Tests.CodeGenSamples.SnapshotNestedPayload();
                        _e3.Deserialize(buffer);
                    }
                    else
                    {
                        _e3 = null;
                    }
                    _list3.Add(_e3);
                }
                this.PayloadList = _list3;
            }
            string _ref4 = buffer.ReadString();
            if (_ref4 == null)
            {
                this.Target = null;
            }
            else
            {
                this.Target = (UnityEngine.GameObject)MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, "Target").FromReference(_ref4, typeof(UnityEngine.GameObject));
            }
            int _n5 = buffer.ReadInt();
            if (_n5 < 0)
            {
                this.Targets = null;
            }
            else
            {
                var _list5 = new System.Collections.Generic.List<UnityEngine.GameObject>(_n5);
                for (int _i5 = 0; _i5 < _n5; _i5++)
                {
                    UnityEngine.GameObject _e5;
                    string _ref6 = buffer.ReadString();
                    if (_ref6 == null)
                    {
                        _e5 = null;
                    }
                    else
                    {
                        _e5 = (UnityEngine.GameObject)MonoBehaviourSnapshotUtility.RequireObjectReferenceResolver(context, "Targets").FromReference(_ref6, typeof(UnityEngine.GameObject));
                    }
                    _list5.Add(_e5);
                }
                this.Targets = _list5;
            }
            this.m_PrivateInt = buffer.ReadInt();
            this.m_PrivatePosition = new UnityEngine.Vector3(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
            int _n7 = buffer.ReadInt();
            if (_n7 < 0)
            {
                this.m_PrivateScores = null;
            }
            else
            {
                var _list7 = new System.Collections.Generic.List<System.Int32>(_n7);
                for (int _i7 = 0; _i7 < _n7; _i7++)
                {
                    System.Int32 _e7;
                    _e7 = buffer.ReadInt();
                    _list7.Add(_e7);
                }
                this.m_PrivateScores = _list7;
            }
        }
    }
}
