//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEditor;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// 扫描 [GenerateEventArgs] attribute 标记的类，自动生成 Clear() + Create(...) 工厂方法
    /// 的 partial class —— 消灭手写 EventArgs 的样板代码。
    ///
    /// 用法：业务在类标记 [GenerateEventArgs]，可写属性即参与 Clear()/Create()：
    ///
    /// <code>
    /// [GenerateEventArgs]
    /// public partial class LoginSuccessEventArgs : FrameworkEventArgs
    /// {
    ///     public string PlayerName { get; private set; }
    ///     public int Level { get; private set; }
    /// }
    /// </code>
    ///
    /// 自动生成：Clear() / Create(playerName, level) 静态工厂方法。
    /// 已接入统一 <see cref="CodeGenHub"/>，可在 Code Generation Window 或 "Generate All" 中运行。
    /// </summary>
    public sealed class EventArgsGenerator : ICodeGenerator
    {
        public const string OutputDir = CodeGenTypeUtil.DefaultAssemblyGeneratedRoot + "/EventArgs";
        private const string ToolName = "EjoyFramework.Core.Unity.Editor.CodeGen.EventArgsGenerator";

        private readonly string m_OutputDir;
        private readonly IEnumerable<Type> m_TargetTypes;
        private readonly bool m_UseAssemblyOutput;

        public EventArgsGenerator()
        {
            m_UseAssemblyOutput = true;
        }

        public EventArgsGenerator(string outputDir, IEnumerable<Type> targetTypes = null)
        {
            m_OutputDir = string.IsNullOrEmpty(outputDir) ? OutputDir : outputDir;
            m_TargetTypes = targetTypes;
            m_UseAssemblyOutput = false;
        }

        public string Id => "eventargs";
        public string DisplayName => "EventArgs Factories";
        public string Description => "[GenerateEventArgs] → Clear()/Create(...) 工厂方法，消灭样板代码。";

        [MenuItem("EjoyFramework/Core/CodeGen/Generate EventArgs Factories")]
        public static void GenerateAll()
        {
            CodeGenHub.RunOne(new EventArgsGenerator());
        }

        public CodeGenResult Run()
        {
            int written = 0, unchanged = 0;
            int skipped = 0;
            var warnings = new List<string>();

            foreach (Type t in GetTargetTypes())
            {
                if (!t.IsClass || t.IsAbstract)
                {
                    skipped++;
                    continue;
                }
                if (t.IsNested)
                {
                    warnings.Add(t.FullName + ": 嵌套 EventArgs 暂不支持生成 partial 工厂，已跳过。");
                    skipped++;
                    continue;
                }
                if (t.ContainsGenericParameters)
                {
                    warnings.Add(t.FullName + ": 泛型定义暂不支持 EventArgs 工厂生成，已跳过。");
                    skipped++;
                    continue;
                }
                if (!typeof(FrameworkEventArgs).IsAssignableFrom(t))
                {
                    warnings.Add(t.FullName + ": 不是 FrameworkEventArgs 子类，已跳过。");
                    skipped++;
                    continue;
                }

                var cb = new CodeBuilder();
                cb.WriteAutoGeneratedHeader(ToolName);
                cb.Line(GenerateForType(t));

                string path;
                if (!TryGetOutputPath(t, warnings, out path))
                {
                    skipped++;
                    continue;
                }
                if (cb.WriteIfChanged(path)) written++;
                else unchanged++;
            }

            return new CodeGenResult
            {
                Written = written,
                Unchanged = unchanged,
                Skipped = skipped,
                Messages = warnings.ToArray(),
            };
        }

        private static string GenerateForType(Type type)
        {
            var sb = new StringBuilder();
            sb.AppendLine("using EjoyFramework.Core;");
            sb.AppendLine();
            sb.AppendLine("namespace " + (type.Namespace ?? "Generated"));
            sb.AppendLine("{");
            sb.AppendLine("    public partial class " + type.Name);
            sb.AppendLine("    {");

            var props = type.GetProperties(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            // Only writable properties participate in Clear()/Create() — the factory cannot assign
            // read-only members, and the param list must match the assignments exactly.
            var writable = props.Where(p => p.CanWrite && p.GetIndexParameters().Length == 0).ToArray();

            // Clear()
            sb.AppendLine("        public override void Clear()");
            sb.AppendLine("        {");
            foreach (var p in writable)
            {
                sb.AppendLine("            " + p.Name + " = default;");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // Create() — params built from the SAME writable set used for the assignments below.
            var paramList = new StringBuilder();
            for (int i = 0; i < writable.Length; i++)
            {
                if (i > 0) paramList.Append(", ");
                paramList.Append(CodeGenTypeUtil.TypeName(writable[i].PropertyType) + " " + CamelCase(writable[i].Name));
            }
            sb.AppendLine("        public static " + type.Name + " Create(" + paramList + ")");
            sb.AppendLine("        {");
            sb.AppendLine("            var e = EjoyFramework.Core.ReferencePool.Acquire<" + type.Name + ">();");
            foreach (var p in writable)
            {
                sb.AppendLine("            e." + p.Name + " = " + CamelCase(p.Name) + ";");
            }
            sb.AppendLine("            return e;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private IEnumerable<Type> GetTargetTypes()
        {
            if (m_TargetTypes != null) return m_TargetTypes;

            var result = new List<Type>();
            foreach (Type t in CodeGenTypeUtil.EnumerateAllTypes())
            {
                if (t.GetCustomAttribute<GenerateEventArgsAttribute>() != null) result.Add(t);
            }
            return result;
        }

        private bool TryGetOutputPath(Type type, List<string> warnings, out string path)
        {
            if (!m_UseAssemblyOutput)
            {
                path = Path.Combine(m_OutputDir, CodeGenTypeUtil.GeneratedFileName(type));
                return true;
            }

            string reason;
            if (CodeGenTypeUtil.TryGetAssemblyGeneratedPath(
                type,
                "EventArgs",
                CodeGenTypeUtil.GeneratedFileName(type),
                out path,
                out reason))
            {
                return true;
            }

            warnings.Add(type.FullName + ": " + reason + " 已跳过。");
            return false;
        }

        private static string CamelCase(string s) => string.IsNullOrEmpty(s) ? s : char.ToLowerInvariant(s[0]) + s.Substring(1);
    }
}
