//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using UnityEditor;
using UnityEngine;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// 扫描 [GenerateSerializer] 类型，生成 partial 的 <c>Serialize(ByteBuffer)</c>/<c>Deserialize(ByteBuffer)</c>
    /// （实现 IBinarySerializable）。逐字段直读直写 ByteBuffer——零反射、零装箱，替代 JsonUtility 反射递归。
    ///
    /// 支持成员：数值基元 / bool / char / string / enum（按底层整型）/ 嵌套 [GenerateSerializer] 类型 /
    /// 上述类型的 List&lt;T&gt; 与一维数组（可嵌套）。不支持的成员被跳过并告警（序列化与反序列化对称跳过，安全）。
    /// </summary>
    public sealed class SerializerGenerator : ICodeGenerator
    {
        public const string OutputDir = CodeGenTypeUtil.DefaultAssemblyGeneratedRoot + "/Serialization";
        private const string ToolName = "EjoyFramework.Core.Unity.Editor.CodeGen.SerializerGenerator";

        private readonly string m_OutputDir;
        private readonly IEnumerable<Type> m_TargetTypes;
        private readonly bool m_UseAssemblyOutput;

        public SerializerGenerator()
        {
            m_UseAssemblyOutput = true;
        }

        public SerializerGenerator(string outputDir, IEnumerable<Type> targetTypes = null)
        {
            m_OutputDir = string.IsNullOrEmpty(outputDir) ? OutputDir : outputDir;
            m_TargetTypes = targetTypes;
            m_UseAssemblyOutput = false;
        }

        public string Id => "serializer";
        public string DisplayName => "Serializer (二进制序列化)";
        public string Description => "[GenerateSerializer] → Serialize/Deserialize(ByteBuffer)，逐字段直读直写，替代 JsonUtility 反射。";

        [MenuItem("EjoyFramework/Core/CodeGen/Generate Serializers")]
        public static void GenerateMenu()
        {
            CodeGenHub.RunOne(new SerializerGenerator());
        }

        public CodeGenResult Run()
        {
            var warnings = new List<string>();
            int written = 0, unchanged = 0, skipped = 0;

            foreach (Type type in GetTargetTypes())
            {
                if (type.IsNested)
                {
                    warnings.Add(type.FullName + ": 嵌套类型暂不支持（需外层 partial），已跳过。");
                    skipped++;
                    continue;
                }
                if (type.ContainsGenericParameters)
                {
                    warnings.Add(type.FullName + ": 泛型定义暂不支持序列化生成，已跳过。");
                    skipped++;
                    continue;
                }

                var cb = new CodeBuilder();
                cb.WriteAutoGeneratedHeader(ToolName);
                cb.Using("EjoyFramework.Core.Serialization");
                cb.BlankLine();

                bool hasNamespace = !string.IsNullOrEmpty(type.Namespace);
                if (hasNamespace) cb.BeginBlock("namespace " + type.Namespace);

                string keyword = type.IsValueType ? "struct" : "class";
                string access = type.IsPublic ? "public" : "internal";
                cb.BeginBlock(access + " partial " + keyword + " " + type.Name + " : IBinarySerializable");

                List<SerializableMember> members = SerializationMemberPolicy.GetSerializableMembers(type);
                members = FilterDuplicateMembers(type, members, warnings, ref skipped);

                int memberSkips = EmitSerialize(cb, type, members, warnings);
                cb.BlankLine();
                EmitDeserialize(cb, type, members, warnings);
                skipped += memberSkips;

                cb.EndBlock();                 // type
                if (hasNamespace) cb.EndBlock(); // namespace

                string path;
                if (!TryGetOutputPath(type, warnings, out path))
                {
                    skipped++;
                    continue;
                }
                if (cb.WriteIfChanged(path)) written++;
                else unchanged++;
            }

            return new CodeGenResult
            {
                Written = written,
                Unchanged = unchanged,
                Skipped = skipped,
                Messages = warnings.ToArray(),
            };
        }

        // ================================================================
        //  方法体生成
        // ================================================================

        private int EmitSerialize(
            CodeBuilder cb,
            Type type,
            List<SerializableMember> members,
            List<string> warnings)
        {
            cb.BeginBlock("public void Serialize(ByteBuffer buffer)");
            var ctx = new EmitCtx(cb, type, warnings);
            foreach (SerializableMember m in members)
            {
                if (!IsSupportedType(m.MemberType, type.Assembly, out string reason))
                {
                    ctx.WarnSkip(m.Name, m.MemberType, reason);
                    continue;
                }
                EmitWrite(ctx, m.MemberType, "this." + m.Name, m.Name);
            }
            cb.EndBlock();
            return ctx.SkippedMembers;
        }

        private void EmitDeserialize(
            CodeBuilder cb,
            Type type,
            List<SerializableMember> members,
            List<string> warnings)
        {
            cb.BeginBlock("public void Deserialize(ByteBuffer buffer)");
            var ctx = new EmitCtx(cb, type, warnings);
            foreach (SerializableMember m in members)
            {
                if (!IsSupportedType(m.MemberType, type.Assembly, out _)) continue;
                EmitRead(ctx, m.MemberType, "this." + m.Name, m.Name);
            }
            cb.EndBlock();
        }

        // ================================================================
        //  写入发射（递归）
        // ================================================================

        private void EmitWrite(EmitCtx ctx, Type type, string expr, string memberName)
        {
            CodeBuilder cb = ctx.Cb;

            string scalar = CodeGenBinaryTypeSupport.ScalarWriteCall(type, expr);
            if (scalar != null) { cb.Line(scalar); return; }

            if (type.IsEnum)
            {
                Type u = Enum.GetUnderlyingType(type);
                cb.Line("buffer." + CodeGenBinaryTypeSupport.ScalarWriteMethod(u)
                    + "((" + CodeGenTypeUtil.TypeName(u) + ")" + expr + ");");
                return;
            }

            if (CodeGenBinaryTypeSupport.TryWriteUnityValue(cb, type, expr)) return;

            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                type,
                ctx.GeneratedAssembly,
                out List<Type> polymorphicCandidates,
                out _))
            {
                CodeGenPolymorphicTypeSupport.EmitWrite(cb, polymorphicCandidates, expr, memberName, ctx.Next());
                return;
            }

            if (IsSerializableComposite(type))
            {
                if (type.IsValueType)
                {
                    cb.Line(expr + ".Serialize(buffer);");
                }
                else
                {
                    cb.Line("buffer.WriteBool(" + expr + " != null);");
                    cb.BeginBlock("if (" + expr + " != null)");
                    cb.Line(expr + ".Serialize(buffer);");
                    cb.EndBlock();
                }
                return;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                EmitWriteCollection(ctx, shape, expr, memberName);
                return;
            }

            // 不支持：对称跳过（写与读都不发射），并告警。
            ctx.WarnSkip(memberName, type, "unsupported type");
        }

        private void EmitWriteCollection(EmitCtx ctx, CodeGenCollectionShape shape, string expr, string memberName)
        {
            CodeBuilder cb = ctx.Cb;
            int n = ctx.Next();

            string countExpr = shape.Kind == CodeGenCollectionKind.Array ? expr + ".Length" : expr + ".Count";
            cb.Line("buffer.WriteInt(" + expr + " != null ? " + countExpr + " : -1);");
            cb.BeginBlock("if (" + expr + " != null)");
            CodeGenBinaryTypeSupport.EmitWriteEqualityComparerGuard(cb, shape, expr, n, memberName);

            if (shape.IsDictionary)
            {
                string keyValueName = "System.Collections.Generic.KeyValuePair<"
                    + CodeGenTypeUtil.TypeName(shape.KeyType) + ", "
                    + CodeGenTypeUtil.TypeName(shape.ValueType) + ">";
                string items = "_items" + n;
                cb.Line("var " + items + " = new System.Collections.Generic.List<" + keyValueName + ">(" + expr + ");");
                string compare;
                CodeGenTypeUtil.TryGetDeterministicCompareExpression(
                    shape.KeyType,
                    "_a" + n + ".Key",
                    "_b" + n + ".Key",
                    out compare);
                cb.Line(items + ".Sort((_a" + n + ", _b" + n + ") => " + compare + ");");
                cb.BeginBlock("foreach (" + keyValueName + " _kv" + n + " in " + items + ")");
                EmitWrite(ctx, shape.KeyType, "_kv" + n + ".Key", memberName);
                EmitWrite(ctx, shape.ValueType, "_kv" + n + ".Value", memberName);
                cb.EndBlock();
            }
            else if (shape.Kind == CodeGenCollectionKind.HashSet)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                string items = "_items" + n;
                cb.Line("var " + items + " = new System.Collections.Generic.List<" + elementName + ">(" + expr + ");");
                string compare;
                CodeGenTypeUtil.TryGetDeterministicCompareExpression(
                    shape.ElementType,
                    "_a" + n,
                    "_b" + n,
                    out compare);
                cb.Line(items + ".Sort((_a" + n + ", _b" + n + ") => " + compare + ");");
                cb.BeginBlock("foreach (" + elementName + " _e" + n + " in " + items + ")");
                EmitWrite(ctx, shape.ElementType, "_e" + n, memberName);
                cb.EndBlock();
            }
            else
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.BeginBlock("foreach (" + elementName + " _e" + n + " in " + expr + ")");
                EmitWrite(ctx, shape.ElementType, "_e" + n, memberName);
                cb.EndBlock();
            }

            cb.EndBlock();
        }

        // ================================================================
        //  读取发射（递归）；target 必须是可赋值左值
        // ================================================================

        private void EmitRead(EmitCtx ctx, Type type, string target, string memberName)
        {
            CodeBuilder cb = ctx.Cb;

            string scalarRead = CodeGenBinaryTypeSupport.ScalarReadExpr(type);
            if (scalarRead != null) { cb.Line(target + " = " + scalarRead + ";"); return; }

            if (type.IsEnum)
            {
                Type u = Enum.GetUnderlyingType(type);
                cb.Line(target + " = (" + CodeGenTypeUtil.TypeName(type) + ")buffer."
                    + CodeGenBinaryTypeSupport.ScalarReadMethod(u) + "();");
                return;
            }

            if (CodeGenBinaryTypeSupport.TryReadUnityValue(cb, type, target, ctx.Next().ToString())) return;

            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(
                type,
                ctx.GeneratedAssembly,
                out List<Type> polymorphicCandidates,
                out _))
            {
                CodeGenPolymorphicTypeSupport.EmitRead(cb, polymorphicCandidates, target, memberName, ctx.Next());
                return;
            }

            if (IsSerializableComposite(type))
            {
                string typeName = CodeGenTypeUtil.TypeName(type);
                if (type.IsValueType)
                {
                    int v = ctx.Next();
                    cb.Line("var _v" + v + " = new " + typeName + "();");
                    cb.Line("_v" + v + ".Deserialize(buffer);");
                    cb.Line(target + " = _v" + v + ";");
                }
                else
                {
                    cb.BeginBlock("if (buffer.ReadBool())");
                    cb.Line(target + " = new " + typeName + "();");
                    cb.Line(target + ".Deserialize(buffer);");
                    cb.EndBlock();
                    cb.BeginBlock("else");
                    cb.Line(target + " = null;");
                    cb.EndBlock();
                }
                return;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                EmitReadCollection(ctx, shape, target, memberName);
                return;
            }

            // 不支持：与 EmitWrite 对称跳过（不计重复告警，写侧已记）。
        }

        private void EmitReadCollection(EmitCtx ctx, CodeGenCollectionShape shape, string target, string memberName)
        {
            CodeBuilder cb = ctx.Cb;
            int n = ctx.Next();

            cb.Line("int _n" + n + " = buffer.ReadInt();");
            cb.BeginBlock("if (_n" + n + " < 0)");
            cb.Line(target + " = null;");
            cb.EndBlock();
            cb.BeginBlock("else");

            if (shape.Kind == CodeGenCollectionKind.Array)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _arr" + n + " = new " + elementName + "[_n" + n + "];");
                cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
                EmitRead(ctx, shape.ElementType, "_arr" + n + "[_i" + n + "]", memberName);
                cb.EndBlock();
                cb.Line(target + " = _arr" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.List)
            {
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.List", "_list", ".Add", true, target, memberName, n);
            }
            else if (shape.Kind == CodeGenCollectionKind.HashSet)
            {
                string comparer = CodeGenBinaryTypeSupport.EmitReadEqualityComparer(cb, shape, n, memberName);
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.HashSet", "_set", ".Add", false, target, memberName, n, comparer);
            }
            else if (shape.Kind == CodeGenCollectionKind.Queue)
            {
                EmitReadAddCollection(ctx, shape.ElementType, "System.Collections.Generic.Queue", "_queue", ".Enqueue", true, target, memberName, n);
            }
            else if (shape.Kind == CodeGenCollectionKind.Stack)
            {
                EmitReadStack(ctx, shape.ElementType, target, memberName, n);
            }
            else if (shape.Kind == CodeGenCollectionKind.Dictionary)
            {
                EmitReadDictionary(ctx, shape, target, memberName, n);
            }

            cb.EndBlock();
        }

        private void EmitReadAddCollection(
            EmitCtx ctx,
            Type elementType,
            string collectionTypeName,
            string variablePrefix,
            string addMethod,
            bool useCapacity,
            string target,
            string memberName,
            int n,
            string comparer = null)
        {
            CodeBuilder cb = ctx.Cb;
            string elementName = CodeGenTypeUtil.TypeName(elementType);
            string variable = variablePrefix + n;
            string ctorArg = comparer ?? (useCapacity ? "_n" + n : string.Empty);
            cb.Line("var " + variable + " = new " + collectionTypeName + "<" + elementName + ">(" + ctorArg + ");");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            cb.Line(elementName + " _e" + n + ";");
            EmitRead(ctx, elementType, "_e" + n, memberName);
            cb.Line(variable + addMethod + "(_e" + n + ");");
            cb.EndBlock();
            cb.Line(target + " = " + variable + ";");
        }

        private void EmitReadStack(EmitCtx ctx, Type elementType, string target, string memberName, int n)
        {
            CodeBuilder cb = ctx.Cb;
            string elementName = CodeGenTypeUtil.TypeName(elementType);
            cb.Line("var _items" + n + " = new " + elementName + "[_n" + n + "];");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            EmitRead(ctx, elementType, "_items" + n + "[_i" + n + "]", memberName);
            cb.EndBlock();
            cb.Line("var _stack" + n + " = new System.Collections.Generic.Stack<" + elementName + ">(_n" + n + ");");
            cb.BeginBlock("for (int _i" + n + " = _n" + n + " - 1; _i" + n + " >= 0; _i" + n + "--)");
            cb.Line("_stack" + n + ".Push(_items" + n + "[_i" + n + "]);");
            cb.EndBlock();
            cb.Line(target + " = _stack" + n + ";");
        }

        private void EmitReadDictionary(
            EmitCtx ctx,
            CodeGenCollectionShape shape,
            string target,
            string memberName,
            int n)
        {
            CodeBuilder cb = ctx.Cb;
            string keyName = CodeGenTypeUtil.TypeName(shape.KeyType);
            string valueName = CodeGenTypeUtil.TypeName(shape.ValueType);
            string comparer = CodeGenBinaryTypeSupport.EmitReadEqualityComparer(cb, shape, n, memberName);
            cb.Line("var _dict" + n + " = new System.Collections.Generic.Dictionary<" + keyName + ", " + valueName + ">(_n" + n + ", " + comparer + ");");
            cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < _n" + n + "; _i" + n + "++)");
            cb.Line(keyName + " _key" + n + ";");
            cb.Line(valueName + " _value" + n + ";");
            EmitRead(ctx, shape.KeyType, "_key" + n, memberName);
            EmitRead(ctx, shape.ValueType, "_value" + n, memberName);
            cb.Line("_dict" + n + ".Add(_key" + n + ", _value" + n + ");");
            cb.EndBlock();
            cb.Line(target + " = _dict" + n + ";");
        }

        // ================================================================
        //  分类辅助
        // ================================================================

        private static bool IsSerializableComposite(Type t)
        {
            return CodeGenPolymorphicTypeSupport.IsSerializableComposite(t);
        }

        private static bool IsSupportedType(Type type, Assembly generatedAssembly, out string reason)
        {
            reason = null;

            if (type == null)
            {
                reason = "null type";
                return false;
            }

            if (CodeGenBinaryTypeSupport.ScalarWriteMethod(type) != null) return true;
            if (type.IsEnum) return true;
            if (CodeGenBinaryTypeSupport.IsUnityValueType(type)) return true;
            if (CodeGenPolymorphicTypeSupport.TryBuildCandidates(type, generatedAssembly, out _, out reason)) return true;
            if (CodeGenPolymorphicTypeSupport.IsPolymorphicContract(type)) return false;
            if (IsSerializableComposite(type))
            {
                if (CanDeserializeComposite(type, generatedAssembly, out reason)) return true;
                return false;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                if (shape.IsDictionary)
                {
                    if (!IsSupportedType(shape.KeyType, generatedAssembly, out reason))
                    {
                        reason = "unsupported dictionary key '" + CodeGenTypeUtil.TypeName(shape.KeyType) + "': " + reason;
                        return false;
                    }
                    if (!CodeGenTypeUtil.HasDeterministicComparer(shape.KeyType))
                    {
                        reason = "dictionary key type must have a deterministic comparer";
                        return false;
                    }
                    if (!IsSupportedType(shape.ValueType, generatedAssembly, out reason))
                    {
                        reason = "unsupported dictionary value '" + CodeGenTypeUtil.TypeName(shape.ValueType) + "': " + reason;
                        return false;
                    }
                    return true;
                }

                if (!IsSupportedType(shape.ElementType, generatedAssembly, out reason))
                {
                    reason = "unsupported collection element '" + CodeGenTypeUtil.TypeName(shape.ElementType) + "': " + reason;
                    return false;
                }
                if (shape.Kind == CodeGenCollectionKind.HashSet
                    && !CodeGenTypeUtil.HasDeterministicComparer(shape.ElementType))
                {
                    reason = "hash set element type must have a deterministic comparer";
                    return false;
                }
                return true;
            }

            reason = "unsupported type";
            return false;
        }

        private IEnumerable<Type> GetTargetTypes()
        {
            return m_TargetTypes ?? CodeGenTypeUtil.FindTypesWithAttribute(typeof(GenerateSerializerAttribute));
        }

        private static List<SerializableMember> FilterDuplicateMembers(
            Type type,
            List<SerializableMember> members,
            List<string> warnings,
            ref int skipped)
        {
            var result = new List<SerializableMember>(members.Count);
            var names = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < members.Count; i++)
            {
                SerializableMember member = members[i];
                if (names.Add(member.Name))
                {
                    result.Add(member);
                    continue;
                }

                skipped++;
                warnings.Add(type.Name + "." + member.Name
                    + ": duplicate serialized member name is ambiguous; hidden inherited member skipped.");
            }
            return result;
        }

        private bool TryGetOutputPath(Type type, List<string> warnings, out string path)
        {
            if (!m_UseAssemblyOutput)
            {
                path = Path.Combine(m_OutputDir, CodeGenTypeUtil.GeneratedFileName(type));
                return true;
            }

            string reason;
            if (CodeGenTypeUtil.TryGetAssemblyGeneratedPath(
                type,
                "Serialization",
                CodeGenTypeUtil.GeneratedFileName(type),
                out path,
                out reason))
            {
                return true;
            }

            warnings.Add(type.FullName + ": " + reason + " 已跳过。");
            return false;
        }

        private static bool CanDeserializeComposite(Type type, Assembly generatedAssembly, out string reason)
        {
            return CodeGenPolymorphicTypeSupport.CanDeserializeConcreteComposite(type, generatedAssembly, out reason);
        }

        // ================================================================
        //  发射上下文：唯一局部名计数 + 告警/跳过统计
        // ================================================================

        private sealed class EmitCtx
        {
            public readonly CodeBuilder Cb;
            private readonly Type m_Type;
            private readonly List<string> m_Warnings;
            private int m_Counter;

            public int SkippedMembers { get; private set; }
            public Assembly GeneratedAssembly => m_Type.Assembly;

            public EmitCtx(CodeBuilder cb, Type type, List<string> warnings)
            {
                Cb = cb;
                m_Type = type;
                m_Warnings = warnings;
            }

            public int Next() => m_Counter++;

            public void WarnSkip(string memberName, Type memberType, string reason)
            {
                SkippedMembers++;
                m_Warnings.Add(m_Type.Name + "." + memberName + ": 不支持的成员类型 '"
                    + CodeGenTypeUtil.TypeName(memberType) + "'，未序列化（" + reason + "）。");
            }
        }
    }
}
