//------------------------------------------------------------
// AUTO-GENERATED by EjoyFramework.Core.Unity.Editor.CodeGen.SerializerGenerator
// DO NOT EDIT - changes will be overwritten on next regen
//------------------------------------------------------------

using EjoyFramework.Core.Serialization;

namespace EjoyFramework.Tests.CodeGenSamples
{
    public partial class BinarySerializerContainerSample : IBinarySerializable
    {
        public void Serialize(ByteBuffer buffer)
        {
            buffer.WriteInt(this.Points != null ? this.Points.Count : -1);
            if (this.Points != null)
            {
                var _comparer0 = this.Points.Comparer;
                byte _comparerKind0;
                if (object.ReferenceEquals(_comparer0, System.Collections.Generic.EqualityComparer<System.String>.Default))
                {
                    _comparerKind0 = 0;
                }
                else if (object.ReferenceEquals(_comparer0, System.StringComparer.Ordinal))
                {
                    _comparerKind0 = 1;
                }
                else if (object.ReferenceEquals(_comparer0, System.StringComparer.OrdinalIgnoreCase))
                {
                    _comparerKind0 = 2;
                }
                else
                {
                    throw new EjoyFramework.Core.FrameworkException("Unsupported string comparer for generated member 'Points'.");
                }
                buffer.WriteByte(_comparerKind0);
                var _items0 = new System.Collections.Generic.List<System.Collections.Generic.KeyValuePair<System.String, UnityEngine.Vector3>>(this.Points);
                _items0.Sort((_a0, _b0) => System.StringComparer.Ordinal.Compare(_a0.Key, _b0.Key));
                foreach (System.Collections.Generic.KeyValuePair<System.String, UnityEngine.Vector3> _kv0 in _items0)
                {
                    buffer.WriteString(_kv0.Key);
                    buffer.WriteFloat(_kv0.Value.x);
                    buffer.WriteFloat(_kv0.Value.y);
                    buffer.WriteFloat(_kv0.Value.z);
                }
            }
            buffer.WriteInt(this.Tags != null ? this.Tags.Count : -1);
            if (this.Tags != null)
            {
                var _comparer1 = this.Tags.Comparer;
                byte _comparerKind1;
                if (object.ReferenceEquals(_comparer1, System.Collections.Generic.EqualityComparer<System.String>.Default))
                {
                    _comparerKind1 = 0;
                }
                else if (object.ReferenceEquals(_comparer1, System.StringComparer.Ordinal))
                {
                    _comparerKind1 = 1;
                }
                else if (object.ReferenceEquals(_comparer1, System.StringComparer.OrdinalIgnoreCase))
                {
                    _comparerKind1 = 2;
                }
                else
                {
                    throw new EjoyFramework.Core.FrameworkException("Unsupported string comparer for generated member 'Tags'.");
                }
                buffer.WriteByte(_comparerKind1);
                var _items1 = new System.Collections.Generic.List<System.String>(this.Tags);
                _items1.Sort((_a1, _b1) => System.StringComparer.Ordinal.Compare(_a1, _b1));
                foreach (System.String _e1 in _items1)
                {
                    buffer.WriteString(_e1);
                }
            }
            buffer.WriteInt(this.Names != null ? this.Names.Count : -1);
            if (this.Names != null)
            {
                foreach (System.String _e2 in this.Names)
                {
                    buffer.WriteString(_e2);
                }
            }
            buffer.WriteInt(this.History != null ? this.History.Count : -1);
            if (this.History != null)
            {
                foreach (System.Int32 _e3 in this.History)
                {
                    buffer.WriteInt(_e3);
                }
            }
            for (int _m4 = 0; _m4 < 16; _m4++) buffer.WriteFloat(this.Matrix[_m4]);
            buffer.WriteInt(this.Mask.value);
        }

        public void Deserialize(ByteBuffer buffer)
        {
            int _n0 = buffer.ReadInt();
            if (_n0 < 0)
            {
                this.Points = null;
            }
            else
            {
                byte _comparerKind0 = buffer.ReadByte();
                System.Collections.Generic.IEqualityComparer<System.String> _comparer0;
                switch (_comparerKind0)
                {
                    case 0: _comparer0 = System.Collections.Generic.EqualityComparer<System.String>.Default; break;
                    case 1: _comparer0 = System.StringComparer.Ordinal; break;
                    case 2: _comparer0 = System.StringComparer.OrdinalIgnoreCase; break;
                    default: throw new EjoyFramework.Core.FrameworkException("Unsupported string comparer kind for generated member 'Points'.");
                }
                var _dict0 = new System.Collections.Generic.Dictionary<System.String, UnityEngine.Vector3>(_n0, _comparer0);
                for (int _i0 = 0; _i0 < _n0; _i0++)
                {
                    System.String _key0;
                    UnityEngine.Vector3 _value0;
                    _key0 = buffer.ReadString();
                    _value0 = new UnityEngine.Vector3(buffer.ReadFloat(), buffer.ReadFloat(), buffer.ReadFloat());
                    _dict0.Add(_key0, _value0);
                }
                this.Points = _dict0;
            }
            int _n1 = buffer.ReadInt();
            if (_n1 < 0)
            {
                this.Tags = null;
            }
            else
            {
                byte _comparerKind1 = buffer.ReadByte();
                System.Collections.Generic.IEqualityComparer<System.String> _comparer1;
                switch (_comparerKind1)
                {
                    case 0: _comparer1 = System.Collections.Generic.EqualityComparer<System.String>.Default; break;
                    case 1: _comparer1 = System.StringComparer.Ordinal; break;
                    case 2: _comparer1 = System.StringComparer.OrdinalIgnoreCase; break;
                    default: throw new EjoyFramework.Core.FrameworkException("Unsupported string comparer kind for generated member 'Tags'.");
                }
                var _set1 = new System.Collections.Generic.HashSet<System.String>(_comparer1);
                for (int _i1 = 0; _i1 < _n1; _i1++)
                {
                    System.String _e1;
                    _e1 = buffer.ReadString();
                    _set1.Add(_e1);
                }
                this.Tags = _set1;
            }
            int _n2 = buffer.ReadInt();
            if (_n2 < 0)
            {
                this.Names = null;
            }
            else
            {
                var _queue2 = new System.Collections.Generic.Queue<System.String>(_n2);
                for (int _i2 = 0; _i2 < _n2; _i2++)
                {
                    System.String _e2;
                    _e2 = buffer.ReadString();
                    _queue2.Enqueue(_e2);
                }
                this.Names = _queue2;
            }
            int _n3 = buffer.ReadInt();
            if (_n3 < 0)
            {
                this.History = null;
            }
            else
            {
                var _items3 = new System.Int32[_n3];
                for (int _i3 = 0; _i3 < _n3; _i3++)
                {
                    _items3[_i3] = buffer.ReadInt();
                }
                var _stack3 = new System.Collections.Generic.Stack<System.Int32>(_n3);
                for (int _i3 = _n3 - 1; _i3 >= 0; _i3--)
                {
                    _stack3.Push(_items3[_i3]);
                }
                this.History = _stack3;
            }
            var _matrix4 = new UnityEngine.Matrix4x4();
            for (int _m4 = 0; _m4 < 16; _m4++) _matrix4[_m4] = buffer.ReadFloat();
            this.Matrix = _matrix4;
            var _mask5 = new UnityEngine.LayerMask();
            _mask5.value = buffer.ReadInt();
            this.Mask = _mask5;
        }
    }
}
