//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.Collections.Generic;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// ConfigBlob 读侧代码生成（运行时 .g.cs）。每张表产出：
    /// <c>XxxRow</c>——只持有 blob 引用与行偏移的 readonly struct，字段属性直接落在编译期常量偏移上，无解析、无装箱；
    /// <c>XxxTable</c>——包住 <c>ConfigTableView</c>，提供 Count / 索引器 / GetById / TryGetById / struct 枚举器。
    /// </summary>
    public static class ConfigBlobReaderEmitter
    {
        /// <summary>生成一张表的读侧源码。</summary>
        public static CodeBuilder Emit(
            ConfigBlobLayout.TableLayout layout,
            string runtimeNamespace,
            string containerNamespace,
            string schemaClassName,
            string toolName)
        {
            var cb = new CodeBuilder();
            cb.WriteAutoGeneratedHeader(toolName, layout.SourcePath);
            cb.Using(containerNamespace);
            cb.BlankLine();
            cb.BeginBlock("namespace " + runtimeNamespace);

            EmitRow(cb, layout, schemaClassName);
            cb.BlankLine();
            EmitTable(cb, layout, schemaClassName);

            cb.EndBlock();
            return cb;
        }

        private static void EmitRow(CodeBuilder cb, ConfigBlobLayout.TableLayout layout, string schemaClassName)
        {
            string rowType = layout.TableName + "Row";

            cb.Line("/// <summary>");
            cb.Line("/// 配置表 " + layout.TableName + " 的一行视图。不复制数据，只记录 blob 与行首偏移；");
            cb.Line("/// 每个属性都是「常量偏移 + 一次直读」，因此取值不产生任何托管分配。");
            cb.Line("/// </summary>");
            cb.BeginBlock("public readonly partial struct " + rowType);

            cb.Line("private readonly ConfigBlob m_Blob;");
            cb.Line("private readonly int m_RowOffset;");
            cb.BlankLine();

            cb.Line("/// <summary>由 " + layout.TableName + "Table 构造，业务侧一般不直接调用。</summary>");
            cb.BeginBlock("public " + rowType + "(ConfigBlob blob, int rowOffset)");
            cb.Line("m_Blob = blob;");
            cb.Line("m_RowOffset = rowOffset;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>是否指向真实数据（default(" + rowType + ") 为 false）。</summary>");
            cb.Line("public bool IsValid => m_Blob != null;");
            cb.BlankLine();
            cb.Line("/// <summary>本行在 blob 内的字节偏移。</summary>");
            cb.Line("public int RowOffset => m_RowOffset;");

            List<ConfigBlobLayout.FieldLayout> fields = layout.FieldsInDeclarationOrder;
            for (int i = 0; i < fields.Count; i++)
            {
                ConfigBlobLayout.FieldLayout field = fields[i];
                string offsetConst = schemaClassName + "." + layout.TableName + "_" + field.Name + "_Offset";
                cb.BlankLine();
                cb.Line("/// <summary>列 " + field.Name + "（" + field.DeclaredType + "，行内偏移 " + field.Offset + "）。</summary>");
                cb.Line("public " + PublicTypeName(field.Kind) + " " + field.Name + " => " + ReadExpression(field.Kind, offsetConst) + ";");
            }

            cb.EndBlock();
        }

        private static void EmitTable(CodeBuilder cb, ConfigBlobLayout.TableLayout layout, string schemaClassName)
        {
            string rowType = layout.TableName + "Row";
            string tableType = layout.TableName + "Table";
            string nameHashConst = schemaClassName + "." + layout.TableName + "NameHash";

            cb.Line("/// <summary>");
            cb.Line("/// 配置表 " + layout.TableName + " 的表视图。构造时定位一次表头，之后的取行都是 O(1) 偏移计算；");
            cb.Line("/// 按主键查找走底层二分（ConfigBlobWriter 另建的 Id 升序索引）。");
            cb.Line("/// </summary>");
            cb.BeginBlock("public readonly partial struct " + tableType);

            cb.Line("private readonly ConfigBlob m_Blob;");
            cb.Line("private readonly ConfigTableView m_View;");
            cb.BlankLine();

            cb.Line("/// <summary>从已打开的 blob 中定位本表；表不存在时抛出。</summary>");
            cb.BeginBlock("public " + tableType + "(ConfigBlob blob)");
            cb.Line("if (blob == null) throw new EjoyFramework.Core.FrameworkException(\"" + tableType + ": blob is null.\");");
            cb.Line("if (!blob.TryGetTable(" + nameHashConst + ", out ConfigTableView view))");
            cb.Indent();
            cb.Line("throw new EjoyFramework.Core.FrameworkException(\"" + tableType + ": table '" + layout.TableName + "' not found in blob.\");");
            cb.Outdent();
            cb.Line("m_Blob = blob;");
            cb.Line("m_View = view;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>是否已绑定到真实 blob（default(" + tableType + ") 为 false）。</summary>");
            cb.Line("public bool IsValid => m_Blob != null;");
            cb.BlankLine();
            cb.Line("/// <summary>行数。</summary>");
            cb.Line("public int Count => m_View.RowCount;");
            cb.BlankLine();
            cb.Line("/// <summary>按下标取行（0 &lt;= index &lt; Count，行序与源表一致）。</summary>");
            cb.Line("public " + rowType + " this[int index] => new " + rowType + "(m_Blob, m_View.GetRowOffsetByIndex(index));");
            cb.BlankLine();

            cb.Line("/// <summary>按主键查找；不存在返回 false 且 row 为 default。</summary>");
            cb.BeginBlock("public bool TryGetById(int id, out " + rowType + " row)");
            cb.Line("int offset = m_View.FindRowOffset(id);");
            cb.BeginBlock("if (offset < 0)");
            cb.Line("row = default;");
            cb.Line("return false;");
            cb.EndBlock();
            cb.Line("row = new " + rowType + "(m_Blob, offset);");
            cb.Line("return true;");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>按主键查找；不存在时抛出（配置缺行属于数据事故，不做静默兜底）。</summary>");
            cb.BeginBlock("public " + rowType + " GetById(int id)");
            cb.Line("int offset = m_View.FindRowOffset(id);");
            cb.Line("if (offset < 0) throw new EjoyFramework.Core.FrameworkException(\"" + tableType + ": row not found, Id=\" + id + \".\");");
            cb.Line("return new " + rowType + "(m_Blob, offset);");
            cb.EndBlock();
            cb.BlankLine();

            cb.Line("/// <summary>无装箱枚举（foreach 直接命中 struct 枚举器）。</summary>");
            cb.Line("public Enumerator GetEnumerator() => new Enumerator(m_Blob, m_View);");
            cb.BlankLine();

            cb.Line("/// <summary>" + tableType + " 的 struct 枚举器。</summary>");
            cb.BeginBlock("public struct Enumerator");
            cb.Line("private readonly ConfigBlob m_Blob;");
            cb.Line("private readonly ConfigTableView m_View;");
            cb.Line("private int m_Index;");
            cb.BlankLine();
            cb.Line("/// <summary>构造枚举器，游标置于首行之前。</summary>");
            cb.BeginBlock("public Enumerator(ConfigBlob blob, ConfigTableView view)");
            cb.Line("m_Blob = blob;");
            cb.Line("m_View = view;");
            cb.Line("m_Index = -1;");
            cb.EndBlock();
            cb.BlankLine();
            cb.Line("/// <summary>当前行。</summary>");
            cb.Line("public " + rowType + " Current => new " + rowType + "(m_Blob, m_View.GetRowOffsetByIndex(m_Index));");
            cb.BlankLine();
            cb.Line("/// <summary>推进游标。</summary>");
            cb.BeginBlock("public bool MoveNext()");
            cb.Line("m_Index++;");
            cb.Line("return m_Index < m_View.RowCount;");
            cb.EndBlock();
            cb.BlankLine();
            cb.Line("/// <summary>游标复位。</summary>");
            cb.Line("public void Reset() => m_Index = -1;");
            cb.EndBlock();

            cb.EndBlock();
        }

        /// <summary>读侧属性暴露的类型：string 列返回 BlobStringHandle（延迟解码，不建 string）。</summary>
        public static string PublicTypeName(ConfigBlobLayout.FieldKind kind)
        {
            return kind == ConfigBlobLayout.FieldKind.String ? "BlobStringHandle" : ConfigBlobLayout.ClrTypeName(kind);
        }

        /// <summary>单字段的读取表达式。</summary>
        public static string ReadExpression(ConfigBlobLayout.FieldKind kind, string offsetConst)
        {
            string at = "m_RowOffset + " + offsetConst;
            switch (kind)
            {
                case ConfigBlobLayout.FieldKind.Int32: return "m_Blob.ReadInt32(" + at + ")";
                case ConfigBlobLayout.FieldKind.Int64: return "m_Blob.ReadInt64(" + at + ")";
                case ConfigBlobLayout.FieldKind.Int16: return "m_Blob.ReadInt16(" + at + ")";
                case ConfigBlobLayout.FieldKind.Byte: return "m_Blob.ReadByte(" + at + ")";
                case ConfigBlobLayout.FieldKind.Bool: return "m_Blob.ReadBoolean(" + at + ")";
                case ConfigBlobLayout.FieldKind.Single: return "m_Blob.ReadSingle(" + at + ")";
                case ConfigBlobLayout.FieldKind.Double: return "m_Blob.ReadDouble(" + at + ")";
                case ConfigBlobLayout.FieldKind.String: return "m_Blob.ReadString(" + at + ")";
                default: throw new FrameworkException("ConfigBlobReaderEmitter: unsupported kind " + kind + ".");
            }
        }
    }
}
