//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.Text;

namespace EjoyFramework.Core.Unity.Editor.Config
{
    /// <summary>
    /// 根据 ConfigTableSchema 生成数据行 C# 源代码。生成的类实现 <c>ISpanDataRow</c>：
    /// 用 <c>TextFieldReader</c> 逐列从字符切片解析（只有 string 列分配），先解析到局部变量、全部成功再赋值；
    /// 列不足或格式错误返回 false（由 DataTableTextParser 带行号告警并跳过该行），不再像 Split + Parse 那样抛异常中断整表。
    /// </summary>
    public static class DataRowGenerator
    {
        public static string Generate(ConfigTableSchema schema, string namespaceName = "EjoyGame.Data")
        {
            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------");
            sb.AppendLine("// AUTO-GENERATED by EjoyFramework.Core ConfigExporter — DO NOT EDIT");
            sb.AppendLine("//------------------------------------------------------------");
            sb.AppendLine("using System;");
            sb.AppendLine("using EjoyFramework.Core;");
            sb.AppendLine("using EjoyFramework.Core.DataTable;");
            sb.AppendLine();
            sb.AppendLine("namespace " + namespaceName);
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class " + schema.TableName + "DataRow : ISpanDataRow");
            sb.AppendLine("    {");
            foreach (var col in schema.Columns)
            {
                sb.AppendLine("        public " + ClrType(col) + " " + col.Name + " { get; private set; }");
            }
            sb.AppendLine();
            sb.AppendLine("        public bool ParseDataRow(string text, object userData)");
            sb.AppendLine("        {");
            sb.AppendLine("            return text != null && ParseDataRow(text.AsSpan(), userData);");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        public bool ParseDataRow(ReadOnlySpan<char> text, object userData)");
            sb.AppendLine("        {");
            sb.AppendLine("            var reader = new TextFieldReader(text, '\\t');");
            for (int i = 0; i < schema.Columns.Count; i++)
            {
                var col = schema.Columns[i];
                sb.AppendLine("            " + ClrType(col) + " c" + i + ";");
                sb.AppendLine("            if (!reader." + ReadMethod(col) + "(out c" + i + ")) return false;");
            }
            for (int i = 0; i < schema.Columns.Count; i++)
            {
                sb.AppendLine("            " + schema.Columns[i].Name + " = c" + i + ";");
            }
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ClrType(ConfigTableSchema.ColumnSchema col)
        {
            switch (col.Type.ToLowerInvariant())
            {
                case "int": case "reference": return "int";
                case "long": return "long";
                case "float": return "float";
                case "bool": return "bool";
                case "string": return "string";
                default: return "string";
            }
        }

        /// <summary>列类型 → TextFieldReader 读取方法（数值走不变文化；布尔宽松接受 1/0、true/false、yes/no）。</summary>
        private static string ReadMethod(ConfigTableSchema.ColumnSchema col)
        {
            switch (col.Type.ToLowerInvariant())
            {
                case "int":
                case "reference":
                    return "TryReadInt32";
                case "long":
                    return "TryReadInt64";
                case "float":
                    return "TryReadSingle";
                case "bool":
                    return "TryReadBoolean";
                case "string":
                default:
                    return "TryReadString";
            }
        }
    }
}
