//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.Collections.Generic;
using System.IO;
using EjoyFramework.Core.Unity.Editor.CodeGen;
using UnityEditor;
using UnityEngine;

namespace EjoyFramework.Core.Unity.Editor.UI.Mvvm
{
    /// <summary>
    /// MVVM UIForm 脚手架。
    /// 选中一个 prefab → 菜单一键产出：
    ///   1. &lt;Form&gt;.cs                (View — MvvmView&lt;TVM&gt; 子类，CreateViewModel 默认实现)
    ///   2. &lt;Form&gt;ViewModel.cs       (空 VM 模板，含 1 个示例 BindableProperty)
    ///   3. 自动遍历 B_*_&lt;Widget&gt; 子节点挂 binder（调 MvvmBindingsGenerator）
    /// 业务后续只需在 VM 里加属性 / 命令。
    /// </summary>
    public static class MvvmFormScaffoldMenu
    {
        private const string DefaultViewDir = "Assets/GameMain/Scripts/UI/Forms";
        private const string DefaultVmDir = "Assets/GameMain/Scripts/UI/ViewModels";
        private const string DefaultNamespace = "EjoyGame.UI";

        [MenuItem("EjoyFramework/Core/UI/Scaffold Form from Selected Prefab")]
        public static void Scaffold()
        {
            var obj = Selection.activeObject;
            if (!(obj is GameObject prefab) || !PrefabUtility.IsPartOfPrefabAsset(prefab))
            {
                EditorUtility.DisplayDialog("MVVM Scaffold", "Select a UIForm prefab asset first.", "OK");
                return;
            }
            string prefabPath = AssetDatabase.GetAssetPath(prefab);
            string formName = prefab.name;
            string vmName = formName + "ViewModel";

            string viewPath = Path.Combine(DefaultViewDir, formName + ".cs");
            string vmPath = Path.Combine(DefaultVmDir, vmName + ".cs");

            if (File.Exists(viewPath) || File.Exists(vmPath))
            {
                if (!EditorUtility.DisplayDialog("MVVM Scaffold",
                    "View or ViewModel file already exists. Overwrite?\n  " + viewPath + "\n  " + vmPath,
                    "Overwrite", "Cancel"))
                    return;
            }

            Directory.CreateDirectory(DefaultViewDir);
            Directory.CreateDirectory(DefaultVmDir);

            WriteViewModel(vmPath, vmName);
            WriteView(viewPath, formName, vmName);

            // 自动挂 binder
            int wired = MvvmBindingsGenerator.WireBindersInternal(prefabPath);

            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog("MVVM Scaffold",
                "Generated:\n" +
                "  " + viewPath + "\n" +
                "  " + vmPath + "\n\n" +
                "Auto-wired " + wired + " binder(s) on " + prefab.name + ".prefab.\n\n" +
                "Next steps:\n" +
                "  - Add [Bindable] properties to " + vmName + "\n" +
                "  - Attach " + formName + " as MonoBehaviour on the prefab root\n" +
                "  - Register prefab in UIComponent.UIFormDefs",
                "OK");
        }

        private static void WriteViewModel(string path, string vmName)
        {
            var cb = new CodeBuilder();
            cb.WriteAutoGeneratedHeader("EjoyFramework.Core.Unity.Editor.UI.Mvvm.MvvmFormScaffoldMenu (initial — safe to edit)");
            cb.Using("EjoyFramework.Core.UI.Mvvm");
            cb.BlankLine();
            cb.BeginBlock("namespace " + DefaultNamespace);
            cb.BeginBlock("public sealed class " + vmName + " : BindableObject");
            cb.Line("// === 示例属性。删/留/扩 ===");
            cb.Line("private string m_Title;");
            cb.Line("public string Title { get { return m_Title; } set { SetField(ref m_Title, value); } }");
            cb.BlankLine();
            cb.Line("// === 示例命令 ===");
            cb.Line("private ICommand m_CloseCommand;");
            cb.BeginBlock("public ICommand CloseCommand");
            cb.Line("get { return m_CloseCommand ?? (m_CloseCommand = new RelayCommand(OnClose)); }");
            cb.EndBlock();
            cb.BlankLine();
            cb.Line("private void OnClose() { /* TODO */ }");
            cb.EndBlock();
            cb.EndBlock();
            cb.WriteIfChanged(path);
        }

        private static void WriteView(string path, string formName, string vmName)
        {
            var cb = new CodeBuilder();
            cb.WriteAutoGeneratedHeader("EjoyFramework.Core.Unity.Editor.UI.Mvvm.MvvmFormScaffoldMenu (initial — safe to edit)");
            cb.Using("EjoyFramework.Core.Unity");
            cb.BlankLine();
            cb.BeginBlock("namespace " + DefaultNamespace);
            cb.BeginBlock("public sealed class " + formName + " : MvvmView<" + vmName + ">");
            cb.BeginBlock("protected override " + vmName + " CreateViewModel(object userData)");
            cb.Line("var vm = new " + vmName + "();");
            cb.Line("// 业务初态：vm.Title = (string)userData;");
            cb.Line("return vm;");
            cb.EndBlock();
            cb.BlankLine();
            cb.BeginBlock("protected override void OnViewModelBound()");
            cb.Line("// 全部 binder 已挂上 VM。业务可订阅 VM 事件或调 ViewModel.<API> 触发首次刷新。");
            cb.EndBlock();
            cb.EndBlock();
            cb.EndBlock();
            cb.WriteIfChanged(path);
        }
    }
}
