//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// 扫描 [GenerateDeepCopy] 类型，生成 partial 的 <c>DeepCopy()</c>/<c>CopyTo(target)</c>
    /// （实现 IDeepCopyable&lt;T&gt;）。逐字段直接赋值；嵌套 [GenerateDeepCopy] 类型递归 DeepCopy，
    /// List&lt;T&gt;/数组逐元素复制——替代"序列化再反序列化"的反射式穷人深拷贝。
    ///
    /// 值类型成员按值复制（若 struct 内含引用字段则为浅拷贝，已在告警中提示）。
    /// 非深拷贝的引用型成员退化为浅拷贝（共享引用）并告警。
    /// </summary>
    public sealed class DeepCopyGenerator : ICodeGenerator
    {
        public const string OutputDir = CodeGenTypeUtil.DefaultAssemblyGeneratedRoot + "/DeepCopy";
        private const string ToolName = "EjoyFramework.Core.Unity.Editor.CodeGen.DeepCopyGenerator";

        private readonly string m_OutputDir;
        private readonly IEnumerable<Type> m_TargetTypes;
        private readonly bool m_UseAssemblyOutput;

        public DeepCopyGenerator()
        {
            m_UseAssemblyOutput = true;
        }

        public DeepCopyGenerator(string outputDir, IEnumerable<Type> targetTypes = null)
        {
            m_OutputDir = string.IsNullOrEmpty(outputDir) ? OutputDir : outputDir;
            m_TargetTypes = targetTypes;
            m_UseAssemblyOutput = false;
        }

        public string Id => "deepcopy";
        public string DisplayName => "DeepCopy (深拷贝/克隆)";
        public string Description => "[GenerateDeepCopy] → DeepCopy()/CopyTo(target)，逐字段直接赋值，替代反射拷贝。";

        [MenuItem("EjoyFramework/Core/CodeGen/Generate DeepCopy")]
        public static void GenerateMenu()
        {
            CodeGenHub.RunOne(new DeepCopyGenerator());
        }

        public CodeGenResult Run()
        {
            var warnings = new List<string>();
            int written = 0, unchanged = 0, skipped = 0;

            foreach (Type type in GetTargetTypes())
            {
                if (type.IsInterface || type.IsAbstract)
                {
                    warnings.Add(type.FullName + ": 抽象类型/接口不支持深拷贝生成，已跳过。");
                    skipped++;
                    continue;
                }
                if (type.IsValueType)
                {
                    warnings.Add(type.FullName + ": 值类型不支持深拷贝生成（按值复制即可），已跳过。");
                    skipped++;
                    continue;
                }
                if (type.IsNested)
                {
                    warnings.Add(type.FullName + ": 嵌套类型暂不支持（需外层 partial），已跳过。");
                    skipped++;
                    continue;
                }
                if (type.ContainsGenericParameters)
                {
                    warnings.Add(type.FullName + ": 泛型定义暂不支持深拷贝生成，已跳过。");
                    skipped++;
                    continue;
                }

                string typeName = type.Name;
                var cb = new CodeBuilder();
                cb.WriteAutoGeneratedHeader(ToolName);
                cb.Using("EjoyFramework.Core.Serialization");
                cb.BlankLine();

                bool hasNamespace = !string.IsNullOrEmpty(type.Namespace);
                if (hasNamespace) cb.BeginBlock("namespace " + type.Namespace);

                string access = type.IsPublic ? "public" : "internal";
                cb.BeginBlock(access + " partial class " + typeName + " : IDeepCopyable<" + typeName + ">");

                // DeepCopy()
                cb.BeginBlock("public " + typeName + " DeepCopy()");
                cb.Line("var copy = new " + typeName + "();");
                cb.Line("CopyTo(copy);");
                cb.Line("return copy;");
                cb.EndBlock();
                cb.BlankLine();

                // CopyTo(target)
                cb.BeginBlock("public void CopyTo(" + typeName + " target)");
                var ctx = new EmitCtx(cb, type, warnings);
                List<SerializableMember> members = SerializationMemberPolicy.GetSerializableMembers(type);
                members = FilterDuplicateMembers(type, members, warnings, ref skipped);
                foreach (SerializableMember m in members)
                {
                    EmitCopy(ctx, m.MemberType, "this." + m.Name, "target." + m.Name, m.Name);
                }
                cb.EndBlock();
                skipped += ctx.ShallowMembers;

                cb.EndBlock();                 // type
                if (hasNamespace) cb.EndBlock(); // namespace

                string path;
                if (!TryGetOutputPath(type, warnings, out path))
                {
                    skipped++;
                    continue;
                }
                if (cb.WriteIfChanged(path)) written++;
                else unchanged++;
            }

            return new CodeGenResult
            {
                Written = written,
                Unchanged = unchanged,
                Skipped = skipped,
                Messages = warnings.ToArray(),
            };
        }

        // src=可读表达式；target=可赋值左值。
        private void EmitCopy(EmitCtx ctx, Type type, string src, string target, string memberName)
        {
            CodeBuilder cb = ctx.Cb;

            if (IsDirectCopy(type))
            {
                cb.Line(target + " = " + src + ";");
                return;
            }

            if (IsDeepCopyable(type))
            {
                cb.Line(target + " = " + src + " != null ? " + src + ".DeepCopy() : null;");
                return;
            }

            CodeGenCollectionShape shape;
            if (CodeGenBinaryTypeSupport.TryGetCollectionShape(type, out shape))
            {
                EmitCopyCollection(ctx, shape, src, target, memberName);
                return;
            }

            // 引用型但不可深拷贝：浅拷贝（共享引用）+ 告警。
            cb.Line(target + " = " + src + ";");
            ctx.WarnShallow(memberName, type);
        }

        private void EmitCopyCollection(
            EmitCtx ctx,
            CodeGenCollectionShape shape,
            string src,
            string target,
            string memberName)
        {
            CodeBuilder cb = ctx.Cb;
            int n = ctx.Next();
            string countExpr = shape.Kind == CodeGenCollectionKind.Array ? src + ".Length" : src + ".Count";

            cb.BeginBlock("if (" + src + " == null)");
            cb.Line(target + " = null;");
            cb.EndBlock();
            cb.BeginBlock("else");

            if (shape.Kind == CodeGenCollectionKind.Array)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _arr" + n + " = new " + elementName + "[" + countExpr + "];");
                cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < " + countExpr + "; _i" + n + "++)");
                EmitCopy(ctx, shape.ElementType, src + "[_i" + n + "]", "_arr" + n + "[_i" + n + "]", memberName);
                cb.EndBlock();
                cb.Line(target + " = _arr" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.List)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _list" + n + " = new System.Collections.Generic.List<" + elementName + ">(" + countExpr + ");");
                cb.BeginBlock("for (int _i" + n + " = 0; _i" + n + " < " + countExpr + "; _i" + n + "++)");
                cb.Line(elementName + " _e" + n + ";");
                EmitCopy(ctx, shape.ElementType, src + "[_i" + n + "]", "_e" + n, memberName);
                cb.Line("_list" + n + ".Add(_e" + n + ");");
                cb.EndBlock();
                cb.Line(target + " = _list" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.Queue)
            {
                EmitCopyForeachCollection(ctx, shape.ElementType, src, "System.Collections.Generic.Queue", "_queue",
                    ".Enqueue", target, memberName, n);
            }
            else if (shape.Kind == CodeGenCollectionKind.HashSet)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _set" + n + " = new System.Collections.Generic.HashSet<" + elementName + ">("
                    + src + ".Comparer);");
                cb.BeginBlock("foreach (" + elementName + " _src" + n + " in " + src + ")");
                cb.Line(elementName + " _e" + n + ";");
                EmitCopy(ctx, shape.ElementType, "_src" + n, "_e" + n, memberName);
                cb.Line("_set" + n + ".Add(_e" + n + ");");
                cb.EndBlock();
                cb.Line(target + " = _set" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.Stack)
            {
                string elementName = CodeGenTypeUtil.TypeName(shape.ElementType);
                cb.Line("var _items" + n + " = new System.Collections.Generic.List<" + elementName + ">(" + src + ");");
                cb.Line("var _stack" + n + " = new System.Collections.Generic.Stack<" + elementName + ">(" + countExpr + ");");
                cb.BeginBlock("for (int _i" + n + " = _items" + n + ".Count - 1; _i" + n + " >= 0; _i" + n + "--)");
                cb.Line(elementName + " _e" + n + ";");
                EmitCopy(ctx, shape.ElementType, "_items" + n + "[_i" + n + "]", "_e" + n, memberName);
                cb.Line("_stack" + n + ".Push(_e" + n + ");");
                cb.EndBlock();
                cb.Line(target + " = _stack" + n + ";");
            }
            else if (shape.Kind == CodeGenCollectionKind.Dictionary)
            {
                string keyName = CodeGenTypeUtil.TypeName(shape.KeyType);
                string valueName = CodeGenTypeUtil.TypeName(shape.ValueType);
                string keyValueName = "System.Collections.Generic.KeyValuePair<" + keyName + ", " + valueName + ">";
                cb.Line("var _dict" + n + " = new System.Collections.Generic.Dictionary<" + keyName + ", "
                    + valueName + ">(" + countExpr + ", " + src + ".Comparer);");
                cb.BeginBlock("foreach (" + keyValueName + " _kv" + n + " in " + src + ")");
                cb.Line(keyName + " _key" + n + ";");
                cb.Line(valueName + " _value" + n + ";");
                EmitCopy(ctx, shape.KeyType, "_kv" + n + ".Key", "_key" + n, memberName);
                EmitCopy(ctx, shape.ValueType, "_kv" + n + ".Value", "_value" + n, memberName);
                cb.Line("_dict" + n + ".Add(_key" + n + ", _value" + n + ");");
                cb.EndBlock();
                cb.Line(target + " = _dict" + n + ";");
            }

            cb.EndBlock();
        }

        private void EmitCopyForeachCollection(
            EmitCtx ctx,
            Type elementType,
            string src,
            string collectionType,
            string localPrefix,
            string addMethod,
            string target,
            string memberName,
            int n)
        {
            CodeBuilder cb = ctx.Cb;
            string elementName = CodeGenTypeUtil.TypeName(elementType);
            cb.Line("var " + localPrefix + n + " = new " + collectionType + "<" + elementName + ">(" + src + ".Count);");
            cb.BeginBlock("foreach (" + elementName + " _src" + n + " in " + src + ")");
            cb.Line(elementName + " _e" + n + ";");
            EmitCopy(ctx, elementType, "_src" + n, "_e" + n, memberName);
            cb.Line(localPrefix + n + addMethod + "(_e" + n + ");");
            cb.EndBlock();
            cb.Line(target + " = " + localPrefix + n + ";");
        }

        // ================================================================
        //  分类辅助
        // ================================================================

        // 直接赋值即可完成复制的类型：基元 / enum / string / 非集合的值类型（按值复制）。
        private static bool IsDirectCopy(Type t)
        {
            if (t.IsPrimitive || t.IsEnum || t == typeof(string)) return true;
            if (t.IsValueType)
            {
                CodeGenCollectionShape shape;
                return !CodeGenBinaryTypeSupport.TryGetCollectionShape(t, out shape);  // 值类型且非集合 → 值复制
            }
            return false;
        }

        private static bool IsDeepCopyable(Type t)
        {
            if (Attribute.IsDefined(t, typeof(GenerateDeepCopyAttribute), false)) return true;
            foreach (Type i in t.GetInterfaces())
            {
                if (i.IsGenericType && i.GetGenericTypeDefinition() == typeof(EjoyFramework.Core.Serialization.IDeepCopyable<>))
                    return true;
            }
            return false;
        }

        private IEnumerable<Type> GetTargetTypes()
        {
            return m_TargetTypes ?? CodeGenTypeUtil.FindTypesWithAttribute(typeof(GenerateDeepCopyAttribute));
        }

        private static List<SerializableMember> FilterDuplicateMembers(
            Type type,
            List<SerializableMember> members,
            List<string> warnings,
            ref int skipped)
        {
            var result = new List<SerializableMember>(members.Count);
            var names = new HashSet<string>(StringComparer.Ordinal);
            for (int i = 0; i < members.Count; i++)
            {
                SerializableMember member = members[i];
                if (names.Add(member.Name))
                {
                    result.Add(member);
                    continue;
                }

                skipped++;
                warnings.Add(type.Name + "." + member.Name
                    + ": duplicate serialized member name is ambiguous; hidden inherited member skipped.");
            }
            return result;
        }

        private bool TryGetOutputPath(Type type, List<string> warnings, out string path)
        {
            if (!m_UseAssemblyOutput)
            {
                path = Path.Combine(m_OutputDir, CodeGenTypeUtil.GeneratedFileName(type));
                return true;
            }

            string reason;
            if (CodeGenTypeUtil.TryGetAssemblyGeneratedPath(
                type,
                "DeepCopy",
                CodeGenTypeUtil.GeneratedFileName(type),
                out path,
                out reason))
            {
                return true;
            }

            warnings.Add(type.FullName + ": " + reason + " 已跳过。");
            return false;
        }

        private sealed class EmitCtx
        {
            public readonly CodeBuilder Cb;
            private readonly Type m_Type;
            private readonly List<string> m_Warnings;
            private int m_Counter;

            public int ShallowMembers { get; private set; }

            public EmitCtx(CodeBuilder cb, Type type, List<string> warnings)
            {
                Cb = cb;
                m_Type = type;
                m_Warnings = warnings;
            }

            public int Next() => m_Counter++;

            public void WarnShallow(string memberName, Type memberType)
            {
                ShallowMembers++;
                m_Warnings.Add(m_Type.Name + "." + memberName + ": 引用型 '"
                    + CodeGenTypeUtil.TypeName(memberType) + "' 不可深拷贝，按浅拷贝（共享引用）处理。");
            }
        }
    }
}
