//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.IO;
using System.Text;

namespace EjoyFramework.Core.Unity.Editor.CodeGen
{
    /// <summary>
    /// 通用 C# 代码字符串生成 helper：缩进 + 块管理 + AUTO-GENERATED header。
    /// 所有 EjoyFramework.Core codegen 工具（EventArgs / DataRow / PacketHandler）的公共基础。
    /// </summary>
    public sealed class CodeBuilder
    {
        private readonly StringBuilder m_Sb = new StringBuilder();
        private int m_Indent;
        private const string IndentUnit = "    ";

        /// <summary>写 file header（标准 EjoyFramework.Core AUTO-GENERATED 注释 + 文件信息）。</summary>
        public CodeBuilder WriteAutoGeneratedHeader(string sourceTool, string sourceFile = null)
        {
            m_Sb.AppendLine("//------------------------------------------------------------");
            m_Sb.AppendLine("// AUTO-GENERATED by " + sourceTool);
            if (!string.IsNullOrEmpty(sourceFile)) m_Sb.AppendLine("// Source: " + sourceFile);
            m_Sb.AppendLine("// DO NOT EDIT — changes will be overwritten on next regen");
            m_Sb.AppendLine("//------------------------------------------------------------");
            m_Sb.AppendLine();
            return this;
        }

        public CodeBuilder Using(string ns) { Line("using " + ns + ";"); return this; }
        public CodeBuilder BlankLine() { m_Sb.AppendLine(); return this; }

        public CodeBuilder Line(string content)
        {
            for (int i = 0; i < m_Indent; i++) m_Sb.Append(IndentUnit);
            m_Sb.AppendLine(content);
            return this;
        }

        /// <summary>开始一个 { } 块。caller 接续 .Indent().Line(...).Outdent().EndBlock()。</summary>
        public CodeBuilder BeginBlock(string header)
        {
            Line(header);
            Line("{");
            m_Indent++;
            return this;
        }

        public CodeBuilder EndBlock()
        {
            m_Indent--;
            Line("}");
            return this;
        }

        public CodeBuilder Indent() { m_Indent++; return this; }
        public CodeBuilder Outdent() { if (m_Indent > 0) m_Indent--; return this; }

        public override string ToString() => m_Sb.ToString();

        /// <summary>
        /// 写入磁盘；自动跳过未变更的文件（保留 Unity meta + 避免无谓重编译）。
        /// 返回 true 表示磁盘有写入，false 表示内容已是最新。
        /// </summary>
        public bool WriteIfChanged(string filePath)
        {
            filePath = CodeGenPath.Resolve(filePath);
            string content = m_Sb.ToString();
            if (File.Exists(filePath))
            {
                string existing = File.ReadAllText(filePath, Encoding.UTF8);
                if (existing.Replace("\r\n", "\n") == content.Replace("\r\n", "\n")) return false;
            }
            CodeGenPath.RequireWritable(filePath);
            string dir = Path.GetDirectoryName(filePath);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(filePath, content, Encoding.UTF8);
            return true;
        }
    }
}
