//------------------------------------------------------------
// EjoyGame Framework Editor
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.Text;

namespace EjoyFramework.Core.Unity.Editor.Config
{
    /// <summary>
    /// 根据 ConfigTableSchema 生成 IDataRow 子类 C# 源代码。
    /// </summary>
    public static class DataRowGenerator
    {
        public static string Generate(ConfigTableSchema schema, string namespaceName = "EjoyGame.Data")
        {
            var sb = new StringBuilder();
            sb.AppendLine("//------------------------------------------------------------");
            sb.AppendLine("// AUTO-GENERATED by EjoyFramework.Core ConfigExporter — DO NOT EDIT");
            sb.AppendLine("//------------------------------------------------------------");
            sb.AppendLine("using System;");
            sb.AppendLine("using EjoyFramework.Core.DataTable;");
            sb.AppendLine();
            sb.AppendLine("namespace " + namespaceName);
            sb.AppendLine("{");
            sb.AppendLine("    public sealed class " + schema.TableName + "DataRow : IDataRow");
            sb.AppendLine("    {");
            foreach (var col in schema.Columns)
            {
                sb.AppendLine("        public " + ClrType(col) + " " + col.Name + " { get; private set; }");
            }
            sb.AppendLine();
            sb.AppendLine("        public bool ParseDataRow(string text, object userData)");
            sb.AppendLine("        {");
            sb.AppendLine("            var cols = text.Split('\\t');");
            sb.AppendLine("            if (cols.Length < " + schema.Columns.Count + ") return false;");
            for (int i = 0; i < schema.Columns.Count; i++)
            {
                var col = schema.Columns[i];
                sb.AppendLine("            " + ParseExpr(col, "cols[" + i + "]"));
            }
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string ClrType(ConfigTableSchema.ColumnSchema col)
        {
            switch (col.Type.ToLowerInvariant())
            {
                case "int": case "reference": return "int";
                case "long": return "long";
                case "float": return "float";
                case "bool": return "bool";
                case "string": return "string";
                default: return "string";
            }
        }

        private static string ParseExpr(ConfigTableSchema.ColumnSchema col, string source)
        {
            switch (col.Type.ToLowerInvariant())
            {
                case "int":
                case "reference":
                    return col.Name + " = int.Parse(" + source + ", System.Globalization.CultureInfo.InvariantCulture);";
                case "long":
                    return col.Name + " = long.Parse(" + source + ", System.Globalization.CultureInfo.InvariantCulture);";
                case "float":
                    return col.Name + " = float.Parse(" + source + ", System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture);";
                case "bool":
                    return col.Name + " = bool.Parse(" + source + ");";
                case "string":
                default:
                    return col.Name + " = " + source + ";";
            }
        }
    }
}
