//------------------------------------------------------------
// EjoyGame Framework Tests
// Copyright (c) 2024-2026 EjoyGame. All rights reserved.
//------------------------------------------------------------

using System.IO;
using NUnit.Framework;
using EjoyFramework.Core.Unity.Editor.CodeGen;

namespace EjoyFramework.Tests
{
    public class CodeBuilderTests
    {
        [Test]
        public void WriteIfChanged_DoesNotRewriteDifferentLineEndings()
        {
            string tmp = Path.Combine(TestTempPaths.Root, "ejoy_cb_test_" + System.Guid.NewGuid().ToString("N") + ".cs");
            try
            {
                File.WriteAllText(tmp, "// hello\n");
                Assert.IsFalse(new CodeBuilder().Line("// hello").WriteIfChanged(tmp));
                Assert.AreEqual("// hello\n", File.ReadAllText(tmp));
            }
            finally { if (File.Exists(tmp)) File.Delete(tmp); }
        }

        [Test]
        public void ImmutablePackage_RejectsChangedAndMissingOutput()
        {
            var package = UnityEditor.PackageManager.PackageInfo.FindForAssetPath("Packages/com.unity.test-framework");
            Assert.That(package, Is.Not.Null, "Test host must install the test framework package.");
            Assert.That(package.source, Is.Not.EqualTo(UnityEditor.PackageManager.PackageSource.Local));
            Assert.That(package.source, Is.Not.EqualTo(UnityEditor.PackageManager.PackageSource.Embedded),
                "This regression requires an immutable test framework dependency.");
            string manifest = Path.Combine(package.resolvedPath, "package.json");
            string before = File.ReadAllText(manifest);
            Assert.Throws<System.InvalidOperationException>(() => new CodeBuilder().Line("// stale").WriteIfChanged(manifest));
            Assert.That(File.ReadAllText(manifest), Is.EqualTo(before));

            string missing = "Packages/com.unity.test-framework/Generated/EjoyGuard_" + System.Guid.NewGuid().ToString("N") + ".cs";
            Assert.Throws<System.InvalidOperationException>(() => new CodeBuilder().Line("// missing").WriteIfChanged(missing));
            Assert.That(File.Exists(CodeGenPath.Resolve(missing)), Is.False);
        }

        [Test]
        public void ConfigBlob_RejectsImmutableOutputBeforeChangingOtherOutputs()
        {
            string root = Path.Combine(TestTempPaths.Root, "ejoy_output_guard_" + System.Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(root);
            string orphan = Path.Combine(root, "Orphan.g.cs");
            string sidecar = Path.Combine(root, "Monsters.types");
            try
            {
                File.WriteAllText(orphan, "preserve orphan");
                File.WriteAllText(orphan + ".meta", "preserve guid");
                File.WriteAllText(sidecar, "preserve sidecar");
                var generator = new ConfigBlobGenerator(new string[0], root,
                    "Packages/com.unity.test-framework/Generated", root);
                Assert.Throws<System.InvalidOperationException>(() => generator.Run());
                Assert.AreEqual("preserve orphan", File.ReadAllText(orphan));
                Assert.AreEqual("preserve guid", File.ReadAllText(orphan + ".meta"));
                Assert.AreEqual("preserve sidecar", File.ReadAllText(sidecar));
            }
            finally { Directory.Delete(root, true); }
        }

        [Test]
        public void Header_Includes_AutoGeneratedMarker()
        {
            var cb = new CodeBuilder().WriteAutoGeneratedHeader("MyTool");
            string s = cb.ToString();
            StringAssert.Contains("AUTO-GENERATED", s);
            StringAssert.Contains("MyTool", s);
            StringAssert.Contains("DO NOT EDIT", s);
        }

        [Test]
        public void BeginBlock_EndBlock_Produces_Indentation()
        {
            var cb = new CodeBuilder()
                .BeginBlock("namespace Foo")
                .BeginBlock("public class Bar")
                .Line("public int X;")
                .EndBlock()
                .EndBlock();
            string s = cb.ToString();
            StringAssert.Contains("namespace Foo", s);
            StringAssert.Contains("    public class Bar", s);
            StringAssert.Contains("        public int X;", s);
        }

        [Test]
        public void Using_AppendsSemicolon()
        {
            string s = new CodeBuilder().Using("System.Collections").ToString();
            StringAssert.Contains("using System.Collections;", s);
        }

        [Test]
        public void WriteIfChanged_True_OnFirstWrite()
        {
            string tmp = Path.Combine(TestTempPaths.Root, "ejoy_cb_test_" + System.Guid.NewGuid().ToString("N") + ".cs");
            try
            {
                var cb = new CodeBuilder().Line("// hello");
                Assert.IsTrue(cb.WriteIfChanged(tmp));
            }
            finally { if (File.Exists(tmp)) File.Delete(tmp); }
        }

        [Test]
        public void WriteIfChanged_False_OnIdenticalContent()
        {
            string tmp = Path.Combine(TestTempPaths.Root, "ejoy_cb_test_" + System.Guid.NewGuid().ToString("N") + ".cs");
            try
            {
                new CodeBuilder().Line("same").WriteIfChanged(tmp);
                Assert.IsFalse(new CodeBuilder().Line("same").WriteIfChanged(tmp), "内容相同应跳过");
            }
            finally { if (File.Exists(tmp)) File.Delete(tmp); }
        }
    }
}
